import Placeholder from "../../../res/productSlider/placeholder.jpg";

const ProductSliderList = [
  {
    id: "8C684734BC7634BC5",
    isFresh: true,
    imageURL: Placeholder,
    name: "Tomato",
    prodRating: 3.5,
    type: "Hybrid",
    category: "Vegetable",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    addedDigit: "37",
    addedUnit: "minutes",
    location: "Aliganj, Bhagalpur",
    isNegotiable: true,
    sellerId: "X874BC36483",
  },
  {
    id: "C3389764B827C683C",
    isFresh: false,
    imageURL: Placeholder,
    name: "Banana",
    prodRating: 3.5,
    type: "Hybrid",
    category: "Fruits",
    basePrice: "24.00",
    pricePerUnit: "dozen",
    addedDigit: "3",
    addedUnit: "hours",
    location: "Sanhoula, Bhagalpur",
    isNegotiable: false,
    sellerId: "4c5t5f4",
  },
  {
    id: "C2874C2CB46327B6",
    isFresh: true,
    imageURL: Placeholder,
    name: "Brinjal",
    prodRating: 3.5,
    type: "Seasonal",
    category: "Vegetable",
    basePrice: "19.00",
    pricePerUnit: "Kg",
    addedDigit: "1",
    addedUnit: "day(s)",
    location: "Tada, Sri City",
    isNegotiable: true,
    sellerId: "X874BC36483",
  },
  {
    id: "V30J3V430N84T9",
    isFresh: false,
    imageURL: Placeholder,
    name: "Rice",
    prodRating: 3.5,
    type: "Sonam-Hybrid (C-212)",
    category: "Grains",
    basePrice: "34.00",
    pricePerUnit: "Kg",
    addedDigit: "36",
    addedUnit: "minutes",
    location: "Aliganj, Bhagalpur",
    isNegotiable: false,
    sellerId: "X874BC36483",
  },
  {
    id: "384HNT3N43H4985T",
    isFresh: false,
    imageURL: Placeholder,
    name: "Tomato",
    prodRating: 3.5,
    type: "Hybrid",
    category: "Vegetable",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    addedDigit: "36",
    addedUnit: "minutes",
    location: "Aliganj, Bhagalpur",
    isNegotiable: true,
    sellerId: "X874BC36483",
  },
  {
    id: "30485NT7C547N4389",
    isFresh: true,
    imageURL: Placeholder,
    name: "Tomato",
    prodRating: 3.5,
    type: "Hybrid",
    category: "Vegetable",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    addedDigit: "36",
    addedUnit: "minutes",
    location: "Aliganj, Bhagalpur",
    isNegotiable: true,
    sellerId: "X874BC36483",
  },
  {
    id: "90348V57T85CM4959",
    isFresh: false,
    imageURL: Placeholder,
    name: "Tomato",
    prodRating: 3.5,
    type: "Hybrid",
    category: "Vegetable",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    addedDigit: "36",
    addedUnit: "minutes",
    location: "Aliganj, Bhagalpur",
    isNegotiable: false,
    sellerId: "X874BC36483",
  },
  {
    id: "9058C7T3454895T",
    isFresh: true,
    imageURL: Placeholder,
    name: "Tomato",
    prodRating: 3.5,
    type: "Hybrid",
    category: "Vegetable",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    addedDigit: "36",
    addedUnit: "minutes",
    location: "Aliganj, Bhagalpur",
    isNegotiable: true,
    sellerId: "X874BC36483",
  },
  {
    id: "C04N7543CNX893N45",
    isFresh: false,
    imageURL: Placeholder,
    name: "Tomato",
    prodRating: 3.5,
    type: "Hybrid",
    category: "Vegetable",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    addedDigit: "36",
    addedUnit: "minutes",
    location: "Aliganj, Bhagalpur",
    isNegotiable: true,
    sellerId: "X874BC36483",
  },
  {
    id: "94587NV958NC5VY458H",
    isFresh: true,
    imageURL: Placeholder,
    name: "Tomato",
    prodRating: 3.5,
    type: "Hybrid",
    category: "Vegetable",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    addedDigit: "36",
    addedUnit: "minutes",
    location: "Aliganj, Bhagalpur",
    isNegotiable: true,
    sellerId: "X874BC36483",
  },
];

export default ProductSliderList;
