const CatMenu = [
  {
    id: "VEG",
    heading: "veggies",
    items: [
      { name: "Alfala" },
      { name: "Alfalfa sprouts" },
      { name: "Amaranth" },
      { name: "Amaranth Leaves" },
      { name: "Arracacha" },
      { name: "Arrowroot" },
      { name: "Artichoke" },
      { name: "Arugula" },
      { name: "Ash gourd" },
      { name: "Asparagus" },
      { name: "Avocado" },
      { name: "Azuki beans" },
      { name: "Bamboo Shoots" },
      { name: "Banana raw" },
      { name: "Banana squash" },
      { name: "Bean Sprouts" },
      { name: "Beans" },
      { name: "Beet Greens" },
      { name: "Beetroot" },
      { name: "Belgian Endive" },
      { name: "Bell Pepper" },
      { name: "Bitter Gourd" },
      { name: "Black beans" },
      { name: "Black eyes peas" },
      { name: "Bok Choi/Pak Choy" },
      { name: "Boriotti bean" },
      { name: "Bottle gourd" },
      { name: "Bread fruit" },
      { name: "Broad beans, Fava" },
      { name: "Broccoli" },
      { name: "Brussels Sprouts" },
      { name: "Burdock Root/Gobo" },
      { name: "Butterhead lettuce" },
      { name: "Butternut squash" },
      { name: "Cabbage" },
      { name: "Cactus leaves" },
      { name: "Calabash" },
      { name: "Cantaloupe" },
      { name: "Cape gooseberry" },
      { name: "Capers" },
      { name: "Carrot" },
      { name: "Cassava/Yuca" },
      { name: "Cauliflower" },
      { name: "Celery" },
      { name: "Celery Root/Celeriac" },
      { name: "Celtuce" },
      { name: "Ceylon spinach" },
      { name: "Chard" },
      { name: "Chayote" },
      { name: "Chickpeas" },
      { name: "Chinese Broccoli" },
      { name: "Chinese mallow" },
      { name: "Chives" },
      { name: "Cluster beans" },
      { name: "Coconut" },
      { name: "Collard Greens" },
      { name: "Colocasia leaves" },
      { name: "Colocasia roots" },
      { name: "Corn/Maize" },
      { name: "Corn/Sweet corn" },
      { name: "Cow pea" },
      { name: "Cucumber" },
      { name: "Curry leaves" },
      { name: "Dabberlocks" },
      { name: "Daikon" },
      { name: "Daikon Radish" },
      { name: "Dandelion Greens" },
      { name: "Delicata" },
      { name: "Dill" },
      { name: "Drum stick" },
      { name: "Earthnut" },
      { name: "Edamame" },
      { name: "Eggplant/Brinjal" },
      { name: "Elephant Garlic" },
      { name: "Endive" },
      { name: "Escarole" },
      { name: "Fat hen" },
      { name: "Fennel" },
      { name: "Fenugreek leaves" },
      { name: "Fiddlehead" },
      { name: "Fluted pumpkin" },
      { name: "French beans" },
      { name: "French sorrel" },
      { name: "Frisee" },
      { name: "Galangal" },
      { name: "Garbanjo beans" },
      { name: "Garlic" },
      { name: "Gem squash" },
      { name: "Ginger" },
      { name: "Goose berry" },
      { name: "Grape Leaves" },
      { name: "Green Beans" },
      { name: "Green Capsicum" },
      { name: "Green chili" },
      { name: "Green Coriander" },
      { name: "Green mustard" },
      { name: "Green onions" },
      { name: "Green peas" },
      { name: "Groundnuts" },
      { name: "Habanero chili" },
      { name: "Hearts of Palm" },
      { name: "Horseradish" },
      { name: "Hubbard squash" },
      { name: "Hyacinth beans" },
      { name: "Ice plant" },
      { name: "Irish moss" },
      { name: "Ivy gourd" },
      { name: "Jack fruit" },
      { name: "Jalapeno" },
      { name: "Jerusalem Artichoke" },
      { name: "Jicama" },
      { name: "Kale" },
      { name: "Kidney beans" },
      { name: "Knolkol" },
      { name: "Kohlrabi" },
      { name: "Kohlrabi Greens" },
      { name: "Lady finger/Okra" },
      { name: "Leeks" },
      { name: "Lemon" },
      { name: "Lemongrass" },
      { name: "Lettuce" },
      { name: "Lima beans" },
      { name: "Lotus Root" },
      { name: "Lotus Seed" },
      { name: "Lotus stem" },
      { name: "Mango raw" },
      { name: "Mint" },
      { name: "Mung beans" },
      { name: "Mushrooms" },
      { name: "Mustard Greens" },
      { name: "Napa Cabbage" },
      { name: "Natal plum" },
      { name: "Navy beans" },
      { name: "Nopales" },
      { name: "Olive" },
      { name: "Onion" },
      { name: "Parsley" },
      { name: "Parsley Root" },
      { name: "Parsnip" },
      { name: "Pea" },
      { name: "Peppers" },
      { name: "Pinto beans" },
      { name: "Plantain" },
      { name: "Plantain raw" },
      { name: "Potato" },
      { name: "Pumpkin" },
      { name: "Purple yam" },
      { name: "Purslane" },
      { name: "Radicchio" },
      { name: "Radish" },
      { name: "Rapini" },
      { name: "Red capsicum" },
      { name: "Ridge gourd" },
      { name: "Rutabaga" },
      { name: "Scallions" },
      { name: "Shallots" },
      { name: "Skirret" },
      { name: "Snack gourd" },
      { name: "Snow peas" },
      { name: "Soy beans" },
      { name: "Spinach" },
      { name: "Split peas" },
      { name: "Squash" },
      { name: "String beans" },
      { name: "Sugar snap peas" },
      { name: "Sweet potato" },
      { name: "Swiss Chard" },
      { name: "Tamarind" },
      { name: "Tapioca" },
      { name: "Taro" },
      { name: "Tat soi" },
      { name: "Tomatillo" },
      { name: "Tomato" },
      { name: "Topinambur" },
      { name: "Turnip" },
      { name: "Turnip Greens" },
      { name: "Vegetables" },
      { name: "Water chestnut" },
      { name: "Water Spinach" },
      { name: "Watercress" },
      { name: "White radish" },
      { name: "Winter Melon" },
      { name: "Yams" },
      { name: "Zucchini" },
    ],
  },
  {
    id: "FRU",
    heading: "fruits",
    items: [
      { name: "Apple" },
      { name: "Apricot" },
      { name: "Avocado" },
      { name: "Bael" },
      { name: "Banana" },
      { name: "Barbadine" },
      { name: "Bell pepper" },
      { name: "Bilberry" },
      { name: "Black sapote" },
      { name: "Blackberry" },
      { name: "Blackcurrant" },
      { name: "Blood orange" },
      { name: "Blueberry" },
      { name: "Boysenberry" },
      { name: "Breadfruit" },
      { name: "Buddha's hand" },
      { name: "Cactus pear" },
      { name: "Cantaloupe" },
      { name: "Custard Apple" },
      { name: "Cherry" },
      { name: "Chico fruit" },
      { name: "Chile pepper" },
      { name: "Cloudberry" },
      { name: "Coconut" },
      { name: "Corn kernel" },
      { name: "Crab apple" },
      { name: "Cranberry" },
      { name: "Cucumber" },
      { name: "Currant" },
      { name: "Damson" },
      { name: "Date" },
      { name: "Dragonfruit" },
      { name: "Fig" },
      { name: "Galia melon" },
      { name: "Goji berry" },
      { name: "Gooseberry" },
      { name: "Grape" },
      { name: "Grapefruit" },
      { name: "Phalsa or falsa" },
      { name: "Guava" },
      { name: "Hala Fruit" },
      { name: "Honeyberry" },
      { name: "Honeydew" },
      { name: "Huckleberry" },
      { name: "Jabuticaba" },
      { name: "Jackfruit" },
      { name: "Jagua" },
      { name: "Jalapeño" },
      { name: "Jamaica Cherry" },
      { name: "Jambul" },
      { name: "Jatoba" },
      { name: "Jenipapo" },
      { name: "Jocote" },
      { name: "Kaffir Lime" },
      { name: "Kakadu Lime" },
      { name: "Kakadu Plum" },
      { name: "Kiwifruit" },
      { name: "Lanzones" },
      { name: "Lapsi" },
      { name: "Legume" },
      { name: "Lemon" },
      { name: "Lemon Aspen" },
      { name: "Leucaena" },
      { name: "Lime" },
      { name: "Lingonberry" },
      { name: "Loganberry" },
      { name: "Longan" },
      { name: "Loquat" },
      { name: "Lucuma" },
      { name: "Lulo" },
      { name: "Lychee" },
      { name: "Mabolo" },
      { name: "Malay Apple" },
      { name: "Mamey Sapote" },
      { name: "Mammee Apple" },
      { name: "Mamoncillo" },
      { name: "Mandarin" },
      { name: "Mandarine" },
      { name: "Mango" },
      { name: "Mangosteen" },
      { name: "Manila Tamarind" },
      { name: "Manoao" },
      { name: "Marang" },
      { name: "Marionberry" },
      { name: "Mayapple" },
      { name: "Mayhaw" },
      { name: "Maypop" },
      { name: "Medlar" },
      { name: "Melinjo" },
      { name: "Melon" },
      { name: "Melon Pear" },
      { name: "Midyim" },
      { name: "Miracle fruit" },
      { name: "Mock Buckthorn" },
      { name: "Mock strawberry" },
      { name: "Monkey Apple" },
      { name: "Monstera" },
      { name: "Monstera Delisiousa" },
      { name: "Morinda" },
      { name: "Mountain Soursop" },
      { name: "Mulberry" },
      { name: "Mundu" },
      { name: "Muntries" },
      { name: "Muskmelons" },
      { name: "Myrtle" },
      { name: "Nageia" },
      { name: "Nance" },
      { name: "Nannyberry" },
      { name: "Naranja" },
      { name: "Naranjilla" },
      { name: "Native Cherry" },
      { name: "Native Currant" },
      { name: "Native Gooseberry" },
      { name: "Nectarine" },
      { name: "Nungu" },
      { name: "Nutmeg" },
      { name: "Oil Palm" },
      { name: "Olive" },
      { name: "Orange" },
      { name: "Orangelo" },
      { name: "Papaya" },
      { name: "Pawpaw" },
      { name: "Pea" },
      { name: "Peach" },
      { name: "Pear" },
      { name: "Pequi" },
      { name: "Persimmon" },
      { name: "Pewa" },
      { name: "Pigface" },
      { name: "Pineapple" },
      { name: "Pineberry" },
      { name: "Pitaya" },
      { name: "Pitomba" },
      { name: "Plantain" },
      { name: "Plum" },
      { name: "Plumcot (or Pluot)" },
      { name: "Podocarpus" },
      { name: "Poha" },
      { name: "Pois Doux" },
      { name: "Pomcite" },
      { name: "Pomegranate" },
      { name: "Pomelo" },
      { name: "Pommecythere" },
      { name: "Pommerac" },
      { name: "Pond Apple" },
      { name: "Prickly Pear" },
      { name: "Prumnopitys" },
      { name: "Prune" },
      { name: "Prune (dried plum)" },
      { name: "Pulasan" },
      { name: "Pummelo" },
      { name: "Pumpkin" },
      { name: "Pupunha" },
      { name: "Purple mangosteen" },
      { name: "Quandong" },
      { name: "Quenepa" },
      { name: "Quince" },
      { name: "Raisin" },
      { name: "Rambutan/Mamin Chino" },
      { name: "Raspberry" },
      { name: "Red Bayberry" },
      { name: "Red Mombin" },
      { name: "Red Mulberry" },
      { name: "Redcurrant" },
      { name: "Rhubarb" },
      { name: "Riberry" },
      { name: "Ridged Gourd" },
      { name: "Rimu" },
      { name: "Rose Apple" },
      { name: "Rose Hip" },
      { name: "Rose Myrtle" },
      { name: "Rose-Leaf Bramble" },
      { name: "Rowan" },
      { name: "Saguaro" },
      { name: "Salak" },
      { name: "Salal berry" },
      { name: "Salmonberry" },
      { name: "Sandpaper Fig" },
      { name: "Santol" },
      { name: "Sapodilla" },
      { name: "Saskatoon" },
      { name: "Saskatoonberry" },
      { name: "Satsuma" },
      { name: "Sea Grape" },
      { name: "Sea-Buckthorn" },
      { name: "Serviceberry" },
      { name: "Shipova" },
      { name: "Siberian Kiwi" },
      { name: "Silkworm Thorn" },
      { name: "Snow berry" },
      { name: "Soursop" },
      { name: "Squash" },
      { name: "Star apple" },
      { name: "Star fruit" },
      { name: "Strawberry" },
      { name: "Surinam cherry" },
      { name: "Tamarillo" },
      { name: "Tamarind" },
      { name: "Tangelo" },
      { name: "Tangerine" },
      { name: "Tanjong" },
      { name: "Taxus Baccata" },
      { name: "Tayberry" },
      { name: "Texas Persimmon" },
      { name: "Thimbleberry" },
      { name: "Tomato" },
      { name: "Toyon" },
      { name: "Ugli fruit" },
      { name: "Ugn" },
      { name: "Vanilla" },
      { name: "Voavanga" },
      { name: "Water Apple" },
      { name: "Watermelon" },
      { name: "Wax Apple" },
      { name: "Wax Gourd" },
      { name: "White Aspen" },
      { name: "White currant" },
      { name: "White Mulberry" },
      { name: "White sapote" },
      { name: "Wild Orange" },
      { name: "Wineberry" },
      { name: "Winter Melon" },
      { name: "Wolfberry" },
      { name: "Wongi" },
      { name: "Wood Apple" },
      { name: "Xigua" },
      { name: "Xylocarp" },
      { name: "Yali Pear" },
      { name: "Yamamomo" },
      { name: "Yangmei" },
      { name: "Yellow Plum" },
      { name: "Yumberry" },
      { name: "Yuzu" },
      { name: "Zucchini" },
    ],
  },
  {
    id: "GRA",
    heading: "cereals",
    items: [
      { name: "Amaranth" },
      { name: "Barley" },
      { name: "Bran" },
      { name: "Broom corn" },
      { name: "Brown rice" },
      { name: "Buckwheat" },
      { name: "Bulgur" },
      { name: "Cereals/ grains" },
      { name: "Corn" },
      { name: "Einkorn" },
      { name: "Farina" },
      { name: "Farro / Emmer" },
      { name: "Fonio" },
      { name: "Freekeh" },
      { name: "Groat" },
      { name: "Hominy" },
      { name: "Kamut" },
      { name: "Kaniwa" },
      { name: "Khorasan Grain" },
      { name: "Maize" },
      { name: "Millet" },
      { name: "Montana flour" },
      { name: "Oats" },
      { name: "Orzo" },
      { name: "Quinoa" },
      { name: "Rice" },
      { name: "Rye" },
      { name: "Semolina" },
      { name: "Sorghum" },
      { name: "Spelt" },
      { name: "Teff" },
      { name: "Triticale" },
      { name: "Wheat" },
      { name: "Wild rice" },
    ],
  },
  {
    id: "PUL",
    heading: "pulses",
    items: [
      { name: "Adzuki Beans" },
      { name: "Anasazi beans" },
      { name: "Appaloosa beans" },
      { name: "Austrian winter peas" },
      { name: "Bambara beans" },
      { name: "Beaten rice" },
      { name: "Beluga Lentils" },
      { name: "Black calypso beans" },
      { name: "Black eyed peas" },
      { name: "Black gram beans" },
      { name: "Black matpe" },
      { name: "Black turtle beans" },
      { name: "Broken wheat" },
      { name: "Brown Lentils" },
      { name: "Chickpea" },
      { name: "Cowpeas" },
      { name: "Faba beans" },
      { name: "Feed peas" },
      { name: "Field beans" },
      { name: "Forage peas" },
      { name: "French Green Lentils" },
      { name: "Great northern beans" },
      { name: "Green Lentils" },
      { name: "Green peas" },
      { name: "Horse gram" },
      { name: "Large faba beans" },
      { name: "lima beans" },
      { name: "Lupins" },
      { name: "Marrowfat peas" },
      { name: "Mung beans" },
      { name: "Pigeon peas" },
      { name: "Pink beans" },
      { name: "Pinto beans" },
      { name: "Puffed rice" },
      { name: "Pulses" },
      { name: "red kidney beans" },
      { name: "Red Lentils" },
      { name: "Romano beans" },
      { name: "Scarlet runner beans" },
      { name: "Split Bengal Gram" },
      { name: "Tongue of fire beans" },
      { name: "Trout beans" },
      { name: "Turkish/ Dew Gram Beans" },
      { name: "Vetches" },
      { name: "White kidney beans" },
      { name: "White navy beans" },
      { name: "Yellow beans" },
      { name: "Yellow peas" },
      { name: "Yellow- eyed peas" },
    ],
  },
  {
    id: "MEA",
    heading: "meat/eggs",
    items: [
      { name: "Anchovy" },
      { name: "Bacon" },
      { name: "Caribou" },
      { name: "Chicken" },
      { name: "Cornish game hen" },
      { name: "Duck" },
      { name: "Eggs" },
      { name: "Brown Eggs" },
      { name: "Emu" },
      { name: "Goat" },
      { name: "Goose" },
      { name: "Grouse" },
      { name: "Ham" },
      { name: "Lamb" },
      { name: "Lobster" },
      { name: "Mutton" },
      { name: "Pastrami" },
      { name: "Pheasant" },
      { name: "Pig" },
      { name: "Pork" },
      { name: "Rabbit" },
      { name: "Salami" },
      { name: "Squab" },
      { name: "Turkey" },
      { name: "Veal" },
      { name: "Venison" },
    ],
  },
  {
    id: "SPI",
    heading: "spices",
    items: [
      { name: "Ajwain" },
      { name: "Allspice" },
      { name: "Ancho chiles" },
      { name: "Anise" },
      { name: "Annatto" },
      { name: "Arrowroot powder" },
      { name: "Asafoetida" },
      { name: "Baharat" },
      { name: "Bay leaf" },
      { name: "Beetroot powder" },
      { name: "Bell peppers" },
      { name: "Black pepper" },
      { name: "Cacao" },
      { name: "Caraway" },
      { name: "Cardamom" },
      { name: "Cayenne pepper" },
      { name: "Celery salt" },
      { name: "Chaat masala" },
      { name: "Chiles" },
      { name: "Chinese cinnamon" },
      { name: "Cinnamon" },
      { name: "Citric acid" },
      { name: "Clove" },
      { name: "Cubeb" },
      { name: "Cubeb berry" },
      { name: "Cumin" },
      { name: "Curry powder" },
      { name: "Fennel flower" },
      { name: "Fenugreek" },
      { name: "File powder" },
      { name: "Furikake seasoning" },
      { name: "Galangal root powder" },
      { name: "Garam masala" },
      { name: "Garlic" },
      { name: "Ghost pepper" },
      { name: "Ginger" },
      { name: "Gochugaru" },
      { name: "Grains of paradise" },
      { name: "Green hatch chiles" },
      { name: "Honey" },
      { name: "Horseradish powder" },
      { name: "Kaffir lime" },
      { name: "Kampot peppercorns" },
      { name: "Long pepper" },
      { name: "Mace" },
      { name: "Malheb" },
      { name: "Maple sugar" },
      { name: "Maras pepper" },
      { name: "Nigella sativa" },
      { name: "Nutmeg" },
      { name: "Onion powder" },
      { name: "Paprika" },
      { name: "Pasilla" },
      { name: "Porcini powder" },
      { name: "Red peppers" },
      { name: "Rose petals" },
      { name: "Saffron" },
      { name: "Salt" },
      { name: "Sansho" },
      { name: "Sesame" },
      { name: "Shallots" },
      { name: "Shichimi togarashi" },
      { name: "Spices" },
      { name: "Star anise" },
      { name: "Turmeric" },
      { name: "Urfa biber" },
      { name: "Vanilla" },
      { name: "Vinegar" },
      { name: "Wasabi" },
      { name: "Za’atar" },
    ],
  },
  {
    id: "SEA",
    heading: "seafood",
    items: [
      { name: "anchovies" },
      { name: "barracuda" },
      { name: "Basa" },
      { name: "Bass" },
      { name: "Black cod/Sablefish" },
      { name: "Blowfish" },
      { name: "Bluefish" },
      { name: "Bombay duck" },
      { name: "Bream" },
      { name: "Brill" },
      { name: "Butter fish" },
      { name: "Catfish" },
      { name: "Caviar" },
      { name: "Clam" },
      { name: "Cockle" },
      { name: "Cod" },
      { name: "Conch" },
      { name: "Crab" },
      { name: "Crayfish" },
      { name: "Cuttlefish" },
      { name: "Dogfish" },
      { name: "Dorade" },
      { name: "Eel" },
      { name: "Flounder" },
      { name: "Grouper" },
      { name: "Haddock" },
      { name: "Hake" },
      { name: "Halibut" },
      { name: "Herring" },
      { name: "Ikura" },
      { name: "Ilish" },
      { name: "John Dory" },
      { name: "Kazunoko" },
      { name: "Lamprey" },
      { name: "Langostino" },
      { name: "Lingcod" },
      { name: "Lobster" },
      { name: "Loco" },
      { name: "Lumpfish roe" },
      { name: "Mackerel" },
      { name: "Mahi Mahi" },
      { name: "Masago" },
      { name: "Monkfish" },
      { name: "Mullet" },
      { name: "Mussel" },
      { name: "Nautilus" },
      { name: "Octopus" },
      { name: "Orange roughy" },
      { name: "Oyster" },
      { name: "Parrotfish" },
      { name: "Patagonian toothfish" },
      { name: "Perch" },
      { name: "Periwinkle" },
      { name: "Pike" },
      { name: "Pilchard" },
      { name: "Pollock" },
      { name: "Pomfret" },
      { name: "Pompano" },
      { name: "Prawns" },
      { name: "Sablefish" },
      { name: "Salmon" },
      { name: "Sanddab" },
      { name: "Sardine" },
      { name: "Scallop" },
      { name: "Sea bass" },
      { name: "Sea cucumber" },
      { name: "Seafood" },
      { name: "Shad" },
      { name: "Shad roe" },
      { name: "Shrimp" },
      { name: "Skate" },
      { name: "Smelt" },
      { name: "Snakehead" },
      { name: "Snapper" },
      { name: "Sole" },
      { name: "Sprat" },
      { name: "Squid" },
      { name: "Sturgeon" },
      { name: "Surimi" },
      { name: "Swordfish" },
      { name: "Tilapia" },
      { name: "Tilefish" },
      { name: "Tobiko" },
      { name: "Trout" },
      { name: "Tuna" },
      { name: "Turbot" },
      { name: "Uni" },
      { name: "Wahoo" },
      { name: "Whitebait" },
      { name: "Whitefish" },
      { name: "Whiting" },
      { name: "Witch" },
    ],
  },
  {
    id: "OIL",
    heading: "oilseeds",
    items: [
      { name: "Apricot" },
      { name: "Canola" },
      { name: "Castor beans" },
      { name: "Chia seeds" },
      { name: "Coconut" },
      { name: "Copra" },
      { name: "Cotton seed" },
      { name: "Crambe" },
      { name: "Flax" },
      { name: "Flaxseed" },
      { name: "Hemp seeds" },
      { name: "Linseeds" },
      { name: "Meadowfoam" },
      { name: "Mustard" },
      { name: "Niger" },
      { name: "Oil palm" },
      { name: "Oilseeds" },
      { name: "Peanut" },
      { name: "Poppy seeds" },
      { name: "Pumpkin seeds" },
      { name: "Rapeseed" },
      { name: "Safflower" },
      { name: "Sesame" },
      { name: "Shea" },
      { name: "Soybeans" },
      { name: "Sunflower" },
      { name: "Tonka bean" },
      { name: "Tung" },
      { name: "Vernonia" },
    ],
  },
  {
    id: "NUT",
    heading: "nuts",
    items: [
      { name: "Acorns" },
      { name: "Almonds" },
      { name: "Areca nuts" },
      { name: "Baru nuts" },
      { name: "Beech" },
      { name: "Black walnuts" },
      { name: "Brazil nuts" },
      { name: "Bread nuts" },
      { name: "Cacao" },
      { name: "Canarium nut" },
      { name: "Candlenut" },
      { name: "Cashews" },
      { name: "Cedar nuts" },
      { name: "Chestnuts" },
      { name: "Chilean hazel" },
      { name: "Coconut" },
      { name: "Gabon nut" },
      { name: "Gingko nuts" },
      { name: "Hazelnuts" },
      { name: "Heartnut" },
      { name: "Jack nuts" },
      { name: "Jelly palm nuts" },
      { name: "Karuka" },
      { name: "Kola nuts" },
      { name: "Kurrajong" },
      { name: "Macadamia nuts" },
      { name: "Malabar chestnut" },
      { name: "Marcona almonds" },
      { name: "Mongongo" },
      { name: "Nuts" },
      { name: "Peanuts" },
      { name: "Pecans" },
      { name: "Pekea nuts" },
      { name: "Pili nuts" },
      { name: "Pine nuts" },
      { name: "Pistachios" },
      { name: "Red bopple nut" },
      { name: "Roasted nuts" },
      { name: "Salted nuts" },
      { name: "Seasoned nuts" },
      { name: "Soy nuts" },
      { name: "Tiger nuts" },
      { name: "Walnuts" },
    ],
  },
  {
    id: "DAI",
    heading: "dairy",
    items: [
      { name: "Amasi" },
      { name: "Anthotyros" },
      { name: "Blaand" },
      { name: "Buffalo milk" },
      { name: "Butter" },
      { name: "Butterfat" },
      { name: "Buttermilk" },
      { name: "Camel milk" },
      { name: "Casein" },
      { name: "Cheese" },
      { name: "Clabber" },
      { name: "Clotted cream" },
      { name: "Condensed milk" },
      { name: "Cottage cheese" },
      { name: "Cow milk" },
      { name: "Cream" },
      { name: "Cream cheese" },
      { name: "Cuajada" },
      { name: "Curd" },
      { name: "Custard" },
      { name: "Dairy products" },
      { name: "Feta" },
      { name: "Filmjoik" },
      { name: "Gelato" },
      { name: "Ghee" },
      { name: "Goat’s milk" },
      { name: "Horse milk" },
      { name: "Ice cream" },
      { name: "Kaymak" },
      { name: "Khoa" },
      { name: "Kulfi" },
      { name: "Kumis" },
      { name: "Lassi" },
      { name: "Leben" },
      { name: "Malai" },
      { name: "Matzoon" },
      { name: "Mozzarella" },
      { name: "Paneer" },
      { name: "Powdered milk" },
      { name: "Pytia" },
      { name: "Qatiq" },
      { name: "Quark" },
      { name: "Reindeer milk" },
      { name: "Ricotta" },
      { name: "Ryazhenka" },
      { name: "Sarasson" },
      { name: "Sheep milk" },
      { name: "Skyr" },
      { name: "So" },
      { name: "Sour cream" },
      { name: "Surmjolk" },
      { name: "Tarhana" },
      { name: "Vaccenic acid" },
      { name: "Varenets" },
      { name: "Whey" },
      { name: "Whipped cream" },
      { name: "Yak butter" },
      { name: "Yak milk" },
      { name: "Ymer" },
      { name: "Yogurt" },
    ],
  },
  {
    id: "HER",
    heading: "herbs",
    items: [
      { name: "Basil" },
      { name: "Bay Laurel" },
      { name: "Bay leaves" },
      { name: "Beefsteak plant" },
      { name: "Borage" },
      { name: "Catnip" },
      { name: "Chamomile" },
      { name: "Chervil" },
      { name: "Chicory" },
      { name: "Chives" },
      { name: "Cicely" },
      { name: "Cilantro" },
      { name: "Cinquefoil" },
      { name: "Columbine" },
      { name: "Common rue" },
      { name: "Common sage" },
      { name: "Coriander" },
      { name: "Dandelion" },
      { name: "dill" },
      { name: "Fennel" },
      { name: "Feverfew" },
      { name: "Foxglove" },
      { name: "Garlic" },
      { name: "Ginger" },
      { name: "Ginkgo biloba" },
      { name: "Ginseng" },
      { name: "Golden rod" },
      { name: "Herbs" },
      { name: "Horehound" },
      { name: "Horseradish" },
      { name: "Hyssop" },
      { name: "Lavender" },
      { name: "Lemon balm" },
      { name: "Lemon beebrush" },
      { name: "Lemon verbena" },
      { name: "Lemongrass" },
      { name: "Liquorice" },
      { name: "Lovage" },
      { name: "Marjoram" },
      { name: "Mexican tea" },
      { name: "Mint" },
      { name: "Mugwort" },
      { name: "Myrtle" },
      { name: "Norwegian angelica" },
      { name: "Oregano" },
      { name: "Parsley" },
      { name: "Peppermint" },
      { name: "Plantago" },
      { name: "Poppy" },
      { name: "Rosemary" },
      { name: "Salad burnet" },
      { name: "Sorrel" },
      { name: "Spearmint" },
      { name: "Sweet Cicely" },
      { name: "Symphytum" },
      { name: "Tarragon" },
      { name: "Thyme" },
      { name: "Turmeric" },
      { name: "Valerian" },
      { name: "Viola" },
      { name: "Winter savory" },
      { name: "Woodruff" },
      { name: "Woodruffe" },
      { name: "Yarrow" },
    ],
  },
  {
    id: "FOD",
    heading: "fodder",
    items: [
      { name: "Alfalfa" },
      { name: "Bagasse" },
      { name: "Barley" },
      { name: "Beets" },
      { name: "Biochar" },
      { name: "Bran" },
      { name: "Bran of barley" },
      { name: "Bran of wheat" },
      { name: "Cabbage" },
      { name: "Carrots" },
      { name: "Cattle cake" },
      { name: "Chaff waste" },
      { name: "Copra waste" },
      { name: "Cottonseed press cake" },
      { name: "Fish meal" },
      { name: "Fodder" },
      { name: "Freshly cut grass" },
      { name: "Grass/lawn clipping" },
      { name: "Green maize" },
      { name: "Green sorghum" },
      { name: "Groundnut press cake" },
      { name: "Hay" },
      { name: "Horse gram" },
      { name: "Leaves" },
      { name: "Meat and bone meal" },
      { name: "Millet" },
      { name: "Molasses" },
      { name: "Native green grass" },
      { name: "Oats" },
      { name: "Oligosaccharides" },
      { name: "Peanut press cake" },
      { name: "Pellets" },
      { name: "Processed insects" },
      { name: "Pumpkins" },
      { name: "Ryegrass" },
      { name: "Safflower press cake" },
      { name: "Seaweed" },
      { name: "Seeds and grains" },
      { name: "Silage" },
      { name: "Single cell protein" },
      { name: "Sorghum" },
      { name: "Soybean press cake" },
      { name: "Sprouted grains/legumes" },
      { name: "Stover waste" },
      { name: "Straw waste" },
      { name: "Sugar beet waste" },
      { name: "Sunflower press cake" },
      { name: "Swedes" },
      { name: "Turnips" },
      { name: "Yeast extract" },
    ],
  },
];

export default CatMenu;
