const CatMenu = [
  {
    id: "VEG",
    heading: "veggies",
    items: [
      { name: "Acorn squash", link: "#" },
      { name: "Ahipa", link: "#" },
      { name: "Alfala", link: "#" },
      { name: "Alfalfa sprouts", link: "#" },
      { name: "Amaranth", link: "#" },
      { name: "Amaranth Leaves", link: "#" },
      { name: "Aonori", link: "#" },
      { name: "Arame", link: "#" },
      { name: "Arracacha", link: "#" },
      { name: "Arrowroot", link: "#" },
      { name: "Artichoke", link: "#" },
      { name: "Arugula", link: "#" },
      { name: "Ash gourd", link: "#" },
      { name: "Asparagus", link: "#" },
      { name: "Avocado", link: "#" },
      { name: "Azuki beans", link: "#" },
      { name: "Bamboo Shoots", link: "#" },
      { name: "Banana raw", link: "#" },
      { name: "Banana squash", link: "#" },
      { name: "Bean Sprouts", link: "#" },
      { name: "Bean sprouts", link: "#" },
      { name: "Beans", link: "#" },
      { name: "Beet", link: "#" },
      { name: "Beet Greens", link: "#" },
      { name: "Beetroot", link: "#" },
      { name: "Belgian Endive", link: "#" },
      { name: "Bell Pepper", link: "#" },
      { name: "Bitter gourd", link: "#" },
      { name: "Bitter Gourd", link: "#" },
      { name: "Black beans", link: "#" },
      { name: "Black eyes peas", link: "#" },
      { name: "Bok Choi/Pak Choy", link: "#" },
      { name: "Boriotti bean", link: "#" },
      { name: "Bottle gourd", link: "#" },
      { name: "Bread fruit", link: "#" },
      { name: "Broad beans, Fava", link: "#" },
      { name: "Broccoli", link: "#" },
      { name: "Brussels Sprouts", link: "#" },
      { name: "Burdock Root/Gobo", link: "#" },
      { name: "Butterhead lettuce", link: "#" },
      { name: "Butternut squash", link: "#" },
      { name: "Cabbage", link: "#" },
      { name: "Cactus leaves", link: "#" },
      { name: "Calabash", link: "#" },
      { name: "Cantaloupe", link: "#" },
      { name: "Cape gooseberry", link: "#" },
      { name: "Capers", link: "#" },
      { name: "Carrot", link: "#" },
      { name: "Cassava", link: "#" },
      { name: "Cassava/Yuca", link: "#" },
      { name: "Cauliflower", link: "#" },
      { name: "Celery", link: "#" },
      { name: "Celery Root/Celeriac", link: "#" },
      { name: "Celtuce", link: "#" },
      { name: "Ceylon spinach", link: "#" },
      { name: "Chard", link: "#" },
      { name: "Chayote", link: "#" },
      { name: "Chickpeas", link: "#" },
      { name: "Chinese Broccoli", link: "#" },
      { name: "Chinese mallow", link: "#" },
      { name: "Chives", link: "#" },
      { name: "Cluster beans", link: "#" },
      { name: "Coconut", link: "#" },
      { name: "Collard Greens", link: "#" },
      { name: "Colocasia leaves", link: "#" },
      { name: "Colocasia roots", link: "#" },
      { name: "Corn/Maize", link: "#" },
      { name: "Corn/Sweet corn", link: "#" },
      { name: "Cow pea", link: "#" },
      { name: "Cucumber", link: "#" },
      { name: "Curry leaves", link: "#" },
      { name: "Dabberlocks", link: "#" },
      { name: "Daikon", link: "#" },
      { name: "Daikon Radish", link: "#" },
      { name: "Dandelion Greens", link: "#" },
      { name: "Delicata", link: "#" },
      { name: "Dill", link: "#" },
      { name: "Drum stick", link: "#" },
      { name: "Earthnut", link: "#" },
      { name: "Edamame", link: "#" },
      { name: "Eggplant/Brinjal", link: "#" },
      { name: "Elephant Garlic", link: "#" },
      { name: "Endive", link: "#" },
      { name: "Escarole", link: "#" },
      { name: "Fat hen", link: "#" },
      { name: "Fennel", link: "#" },
      { name: "Fenugreek leaves", link: "#" },
      { name: "Fiddlehead", link: "#" },
      { name: "Fluted pumpkin", link: "#" },
      { name: "French beans", link: "#" },
      { name: "French sorrel", link: "#" },
      { name: "Frisee", link: "#" },
      { name: "Galangal", link: "#" },
      { name: "Garbanjo beans", link: "#" },
      { name: "Garlic", link: "#" },
      { name: "Gem squash", link: "#" },
      { name: "Ginger", link: "#" },
      { name: "Goose berry", link: "#" },
      { name: "Grape Leaves", link: "#" },
      { name: "Green Beans", link: "#" },
      { name: "Green Capsicum", link: "#" },
      { name: "Green chili", link: "#" },
      { name: "Green Coriander", link: "#" },
      { name: "Green mustard", link: "#" },
      { name: "Green onions", link: "#" },
      { name: "Green peas", link: "#" },
      { name: "Groundnuts", link: "#" },
      { name: "Habanero chili", link: "#" },
      { name: "Hearts of Palm", link: "#" },
      { name: "Horseradish", link: "#" },
      { name: "Hubbard squash", link: "#" },
      { name: "Hyacinth beans", link: "#" },
      { name: "Ice plant", link: "#" },
      { name: "Irish moss", link: "#" },
      { name: "Ivy gourd", link: "#" },
      { name: "Jack fruit", link: "#" },
      { name: "Jalapeno", link: "#" },
      { name: "Jerusalem Artichoke", link: "#" },
      { name: "Jicama", link: "#" },
      { name: "Kale", link: "#" },
      { name: "Kidney beans", link: "#" },
      { name: "Knolkol", link: "#" },
      { name: "Kohlrabi", link: "#" },
      { name: "Kohlrabi Greens", link: "#" },
      { name: "Lady finger/Okra", link: "#" },
      { name: "Leeks", link: "#" },
      { name: "Lemon", link: "#" },
      { name: "Lemongrass", link: "#" },
      { name: "Lettuce", link: "#" },
      { name: "Lima beans", link: "#" },
      { name: "Lotus Root", link: "#" },
      { name: "Lotus Seed", link: "#" },
      { name: "Lotus stem", link: "#" },
      { name: "Maize", link: "#" },
      { name: "Mango raw", link: "#" },
      { name: "Mint", link: "#" },
      { name: "Mung beans", link: "#" },
      { name: "Mushrooms", link: "#" },
      { name: "Mustard Greens", link: "#" },
      { name: "Napa Cabbage", link: "#" },
      { name: "Natal plum", link: "#" },
      { name: "Navy beans", link: "#" },
      { name: "Nopales", link: "#" },
      { name: "Okra", link: "#" },
      { name: "Olive", link: "#" },
      { name: "Onion", link: "#" },
      { name: "Parsley", link: "#" },
      { name: "Parsley Root", link: "#" },
      { name: "Parsnip", link: "#" },
      { name: "Pea", link: "#" },
      { name: "Peppers", link: "#" },
      { name: "Pinto beans", link: "#" },
      { name: "Plantain", link: "#" },
      { name: "Plantain raw", link: "#" },
      { name: "Potato", link: "#" },
      { name: "Pumpkin", link: "#" },
      { name: "Purple yam", link: "#" },
      { name: "Purslane", link: "#" },
      { name: "Radicchio", link: "#" },
      { name: "Radish", link: "#" },
      { name: "Rapini", link: "#" },
      { name: "Red capsicum", link: "#" },
      { name: "Ridge gourd", link: "#" },
      { name: "Rutabaga", link: "#" },
      { name: "Scallions", link: "#" },
      { name: "Shallots", link: "#" },
      { name: "Skirret", link: "#" },
      { name: "Snack gourd", link: "#" },
      { name: "Snow peas", link: "#" },
      { name: "Soy beans", link: "#" },
      { name: "Spinach", link: "#" },
      { name: "Split peas", link: "#" },
      { name: "Squash", link: "#" },
      { name: "String beans", link: "#" },
      { name: "Sugar snap peas", link: "#" },
      { name: "Sweet potato", link: "#" },
      { name: "Swiss Chard", link: "#" },
      { name: "Tamarind", link: "#" },
      { name: "Tapioca", link: "#" },
      { name: "Taro", link: "#" },
      { name: "Tat soi", link: "#" },
      { name: "Tomatillo", link: "#" },
      { name: "Tomato", link: "#" },
      { name: "Topinambur", link: "#" },
      { name: "Turnip", link: "#" },
      { name: "Turnip Greens", link: "#" },
      { name: "Vegetables", link: "#" },
      { name: "Water chestnut", link: "#" },
      { name: "Water Spinach", link: "#" },
      { name: "Watercress", link: "#" },
      { name: "White radish", link: "#" },
      { name: "Winter Melon", link: "#" },
      { name: "Yams", link: "#" },
      { name: "Zucchini", link: "#" },
    ],
  },
  {
    id: "FRU",
    heading: "fruits",
    items: [
      { name: "Abiu", link: "#" },
      { name: "Acerola", link: "#" },
      { name: "Ackee", link: "#" },
      { name: "Ambarella", link: "#" },
      { name: "Apple", link: "#" },
      { name: "Apricot", link: "#" },
      { name: "Araza", link: "#" },
      { name: "Avocado", link: "#" },
      { name: "Açaí", link: "#" },
      { name: "Babaco", link: "#" },
      { name: "Bael", link: "#" },
      { name: "Banana", link: "#" },
      { name: "Barbadine", link: "#" },
      { name: "Bell pepper", link: "#" },
      { name: "Bilberry", link: "#" },
      { name: "Black sapote", link: "#" },
      { name: "Blackberry", link: "#" },
      { name: "Blackcurrant", link: "#" },
      { name: "Blood orange", link: "#" },
      { name: "Blueberry", link: "#" },
      { name: "Boysenberry", link: "#" },
      { name: "Breadfruit", link: "#" },
      { name: "Buddha's hand", link: "#" },
      { name: "Cactus pear", link: "#" },
      { name: "Cantaloupe", link: "#" },
      { name: "Custard Apple", link: "#" },
      { name: "Cherry", link: "#" },
      { name: "Chico fruit", link: "#" },
      { name: "Chile pepper", link: "#" },
      { name: "Clementine", link: "#" },
      { name: "Cloudberry", link: "#" },
      { name: "Coconut", link: "#" },
      { name: "Corn kernel", link: "#" },
      { name: "Crab apple", link: "#" },
      { name: "Cranberry", link: "#" },
      { name: "Cucumber", link: "#" },
      { name: "Currant", link: "#" },
      { name: "Damson", link: "#" },
      { name: "Date", link: "#" },
      { name: "Dewberry", link: "#" },
      { name: "Dragonfruit", link: "#" },
      { name: "Durian", link: "#" },
      { name: "Eggplant", link: "#" },
      { name: "Elderberry", link: "#" },
      { name: "Elephant fruit", link: "#" },
      { name: "Feijoa", link: "#" },
      { name: "Fig", link: "#" },
      { name: "Fruits", link: "#" },
      { name: "Galia melon", link: "#" },
      { name: "Goji berry", link: "#" },
      { name: "Gooseberry", link: "#" },
      { name: "Grape", link: "#" },
      { name: "Grapefruit", link: "#" },
      { name: "Phalsa or falsa", link: "#" },
      { name: "Guava", link: "#" },
      { name: "Hala Fruit", link: "#" },
      { name: "Honeyberry", link: "#" },
      { name: "Honeydew", link: "#" },
      { name: "Huckleberry", link: "#" },
      { name: "Jabuticaba", link: "#" },
      { name: "Jackfruit", link: "#" },
      { name: "Jagua", link: "#" },
      { name: "Jalapeño", link: "#" },
      { name: "Jamaica Cherry", link: "#" },
      { name: "Jambul", link: "#" },
      { name: "Japanese Bayberry", link: "#" },
      { name: "Japanese plum", link: "#" },
      { name: "Japanese Raisin", link: "#" },
      { name: "Jasmine", link: "#" },
      { name: "Jatoba", link: "#" },
      { name: "Jenipapo", link: "#" },
      { name: "Jocote", link: "#" },
      { name: "Jostaberry", link: "#" },
      { name: "Jujube", link: "#" },
      { name: "Juniper berry", link: "#" },
      { name: "Kaffir Lime", link: "#" },
      { name: "Kahikatea", link: "#" },
      { name: "Kakadu Lime", link: "#" },
      { name: "Kakadu Plum", link: "#" },
      { name: "Kandis Fruit", link: "#" },
      { name: "Karkalla", link: "#" },
      { name: "Keppel Fruit", link: "#" },
      { name: "Key Lime", link: "#" },
      { name: "Kiwano (horned melon)", link: "#" },
      { name: "Kiwifruit", link: "#" },
      { name: "Kumquat", link: "#" },
      { name: "Kundong", link: "#" },
      { name: "Kutjera", link: "#" },
      { name: "Lablab", link: "#" },
      { name: "Lady Apple", link: "#" },
      { name: "Langsat", link: "#" },
      { name: "Lanzones", link: "#" },
      { name: "Lapsi", link: "#" },
      { name: "Legume", link: "#" },
      { name: "Lemon", link: "#" },
      { name: "Lemon Aspen", link: "#" },
      { name: "Leucaena", link: "#" },
      { name: "Lillipilli", link: "#" },
      { name: "Lime", link: "#" },
      { name: "Lingonberry", link: "#" },
      { name: "Loganberry", link: "#" },
      { name: "Longan", link: "#" },
      { name: "Loquat", link: "#" },
      { name: "Lucuma", link: "#" },
      { name: "Lulo", link: "#" },
      { name: "Lychee", link: "#" },
      { name: "Mabolo", link: "#" },
      { name: "Macadamia", link: "#" },
      { name: "Malay Apple", link: "#" },
      { name: "Mamey Sapote", link: "#" },
      { name: "Mammee Apple", link: "#" },
      { name: "Mamoncillo", link: "#" },
      { name: "Mandarin", link: "#" },
      { name: "Mandarine", link: "#" },
      { name: "Mango", link: "#" },
      { name: "Mangosteen", link: "#" },
      { name: "Manila Tamarind", link: "#" },
      { name: "Manoao", link: "#" },
      { name: "Marang", link: "#" },
      { name: "Marionberry", link: "#" },
      { name: "Mayapple", link: "#" },
      { name: "Mayhaw", link: "#" },
      { name: "Maypop", link: "#" },
      { name: "Medlar", link: "#" },
      { name: "Melinjo", link: "#" },
      { name: "Melon", link: "#" },
      { name: "Melon Pear", link: "#" },
      { name: "Midyim", link: "#" },
      { name: "Miracle fruit", link: "#" },
      { name: "Mock Buckthorn", link: "#" },
      { name: "Mock strawberry", link: "#" },
      { name: "Monkey Apple", link: "#" },
      { name: "Monstera", link: "#" },
      { name: "Monstera Delisiousa", link: "#" },
      { name: "Morinda", link: "#" },
      { name: "Mountain Soursop", link: "#" },
      { name: "Mulberry", link: "#" },
      { name: "Mundu", link: "#" },
      { name: "Muntries", link: "#" },
      { name: "Muskmelons", link: "#" },
      { name: "Myrtle", link: "#" },
      { name: "Nageia", link: "#" },
      { name: "Nance", link: "#" },
      { name: "Nannyberry", link: "#" },
      { name: "Naranja", link: "#" },
      { name: "Naranjilla", link: "#" },
      { name: "Native Cherry", link: "#" },
      { name: "Native Currant", link: "#" },
      { name: "Native Gooseberry", link: "#" },
      { name: "Nectarine", link: "#" },
      { name: "Noni", link: "#" },
      { name: "Nungu", link: "#" },
      { name: "Nutmeg", link: "#" },
      { name: "Oil Palm", link: "#" },
      { name: "Olallieberry", link: "#" },
      { name: "Old World Sycomore", link: "#" },
      { name: "Olive", link: "#" },
      { name: "Orange", link: "#" },
      { name: "Orangelo", link: "#" },
      { name: "Oregon Grape", link: "#" },
      { name: "Otaheite Apple", link: "#" },
      { name: "Papaya", link: "#" },
      { name: "Passionfruit", link: "#" },
      { name: "Pawpaw", link: "#" },
      { name: "Pea", link: "#" },
      { name: "Peach", link: "#" },
      { name: "Pear", link: "#" },
      { name: "Pequi", link: "#" },
      { name: "Persimmon", link: "#" },
      { name: "Pewa", link: "#" },
      { name: "Pigface", link: "#" },
      { name: "Pineapple", link: "#" },
      { name: "Pineberry", link: "#" },
      { name: "Pitaya", link: "#" },
      { name: "Pitomba", link: "#" },
      { name: "Plantain", link: "#" },
      { name: "Plum", link: "#" },
      { name: "Plumcot (or Pluot)", link: "#" },
      { name: "Podocarpus", link: "#" },
      { name: "Poha", link: "#" },
      { name: "Pois Doux", link: "#" },
      { name: "Pomcite", link: "#" },
      { name: "Pomegranate", link: "#" },
      { name: "Pomelo", link: "#" },
      { name: "Pommecythere", link: "#" },
      { name: "Pommerac", link: "#" },
      { name: "Pond Apple", link: "#" },
      { name: "Prickly Pear", link: "#" },
      { name: "Prumnopitys", link: "#" },
      { name: "Prune", link: "#" },
      { name: "Prune (dried plum)", link: "#" },
      { name: "Pulasan", link: "#" },
      { name: "Pummelo", link: "#" },
      { name: "Pumpkin", link: "#" },
      { name: "Pupunha", link: "#" },
      { name: "Purple mangosteen", link: "#" },
      { name: "Quandong", link: "#" },
      { name: "Quenepa", link: "#" },
      { name: "Quince", link: "#" },
      { name: "Raisin", link: "#" },
      { name: "Rambutan/Mamin Chino", link: "#" },
      { name: "Raspberry", link: "#" },
      { name: "Red Bayberry", link: "#" },
      { name: "Red Mombin", link: "#" },
      { name: "Red Mulberry", link: "#" },
      { name: "Redcurrant", link: "#" },
      { name: "Rhubarb", link: "#" },
      { name: "Riberry", link: "#" },
      { name: "Ridged Gourd", link: "#" },
      { name: "Rimu", link: "#" },
      { name: "Rose Apple", link: "#" },
      { name: "Rose Hip", link: "#" },
      { name: "Rose Myrtle", link: "#" },
      { name: "Rose-Leaf Bramble", link: "#" },
      { name: "Rowan", link: "#" },
      { name: "Saguaro", link: "#" },
      { name: "Salak", link: "#" },
      { name: "Salal berry", link: "#" },
      { name: "Salmonberry", link: "#" },
      { name: "Sandpaper Fig", link: "#" },
      { name: "Santol", link: "#" },
      { name: "Sapodilla", link: "#" },
      { name: "Saskatoon", link: "#" },
      { name: "Saskatoonberry", link: "#" },
      { name: "Satsuma", link: "#" },
      { name: "Sea Grape", link: "#" },
      { name: "Sea-Buckthorn", link: "#" },
      { name: "Serviceberry", link: "#" },
      { name: "Shipova", link: "#" },
      { name: "Siberian Kiwi", link: "#" },
      { name: "Silkworm Thorn", link: "#" },
      { name: "Snow berry", link: "#" },
      { name: "Soursop", link: "#" },
      { name: "Squash", link: "#" },
      { name: "Star apple", link: "#" },
      { name: "Star fruit", link: "#" },
      { name: "Strawberry", link: "#" },
      { name: "Surinam cherry", link: "#" },
      { name: "Tamarillo", link: "#" },
      { name: "Tamarind", link: "#" },
      { name: "Tangelo", link: "#" },
      { name: "Tangerine", link: "#" },
      { name: "Tanjong", link: "#" },
      { name: "Taxus Baccata", link: "#" },
      { name: "Tayberry", link: "#" },
      { name: "Texas Persimmon", link: "#" },
      { name: "Thimbleberry", link: "#" },
      { name: "Tomato", link: "#" },
      { name: "Toyon", link: "#" },
      { name: "Ugli fruit", link: "#" },
      { name: "Ugn", link: "#" },
      { name: "Vanilla", link: "#" },
      { name: "Voavanga", link: "#" },
      { name: "Water Apple", link: "#" },
      { name: "Watermelon", link: "#" },
      { name: "Wax Apple", link: "#" },
      { name: "Wax Gourd", link: "#" },
      { name: "White Aspen", link: "#" },
      { name: "White currant", link: "#" },
      { name: "White Mulberry", link: "#" },
      { name: "White sapote", link: "#" },
      { name: "Wild Orange", link: "#" },
      { name: "Wineberry", link: "#" },
      { name: "Winter Melon", link: "#" },
      { name: "Wolfberry", link: "#" },
      { name: "Wongi", link: "#" },
      { name: "Wood Apple", link: "#" },
      { name: "Xigua", link: "#" },
      { name: "Xylocarp", link: "#" },
      { name: "Yali Pear", link: "#" },
      { name: "Yamamomo", link: "#" },
      { name: "Yangmei", link: "#" },
      { name: "Yellow Plum", link: "#" },
      { name: "Yumberry", link: "#" },
      { name: "Yuzu", link: "#" },
      { name: "Zucchini", link: "#" },
    ],
  },
  {
    id: "GRA",
    heading: "cereals",
    items: [
      { name: "Amaranth", link: "#" },
      { name: "Barley", link: "#" },
      { name: "Bran", link: "#" },
      { name: "Broom corn", link: "#" },
      { name: "Brown rice", link: "#" },
      { name: "Buckwheat", link: "#" },
      { name: "Bulgur", link: "#" },
      { name: "Cereals/ grains", link: "#" },
      { name: "Corn", link: "#" },
      { name: "Einkorn", link: "#" },
      { name: "Farina", link: "#" },
      { name: "Farro / Emmer", link: "#" },
      { name: "Fonio", link: "#" },
      { name: "Freekeh", link: "#" },
      { name: "Groat", link: "#" },
      { name: "Hominy", link: "#" },
      { name: "Kamut", link: "#" },
      { name: "Kaniwa", link: "#" },
      { name: "Khorasan Grain", link: "#" },
      { name: "Maize", link: "#" },
      { name: "Millet", link: "#" },
      { name: "Montana flour", link: "#" },
      { name: "Oats", link: "#" },
      { name: "Orzo", link: "#" },
      { name: "Quinoa", link: "#" },
      { name: "Rice", link: "#" },
      { name: "Rye", link: "#" },
      { name: "Semolina", link: "#" },
      { name: "Sorghum", link: "#" },
      { name: "Spelt", link: "#" },
      { name: "Teff", link: "#" },
      { name: "Triticale", link: "#" },
      { name: "Wheat", link: "#" },
      { name: "Wild rice", link: "#" },
    ],
  },
  {
    id: "PUL",
    heading: "pulses",
    items: [
      { name: "Adzuki Beans", link: "#" },
      { name: "Anasazi beans", link: "#" },
      { name: "Appaloosa beans", link: "#" },
      { name: "Austrian winter peas", link: "#" },
      { name: "Bambara beans", link: "#" },
      { name: "Beaten rice", link: "#" },
      { name: "Beluga Lentils", link: "#" },
      { name: "Black calypso beans", link: "#" },
      { name: "Black eyed peas", link: "#" },
      { name: "Black gram beans", link: "#" },
      { name: "Black matpe", link: "#" },
      { name: "Black turtle beans", link: "#" },
      { name: "Broken wheat", link: "#" },
      { name: "Brown Lentils", link: "#" },
      { name: "Chickpea", link: "#" },
      { name: "Cowpeas", link: "#" },
      { name: "Faba beans", link: "#" },
      { name: "Feed peas", link: "#" },
      { name: "Field beans", link: "#" },
      { name: "Forage peas", link: "#" },
      { name: "French Green Lentils", link: "#" },
      { name: "Great northern beans", link: "#" },
      { name: "Green Lentils", link: "#" },
      { name: "Green peas", link: "#" },
      { name: "Horse gram", link: "#" },
      { name: "Large faba beans", link: "#" },
      { name: "lima beans", link: "#" },
      { name: "Lupins", link: "#" },
      { name: "Marrowfat peas", link: "#" },
      { name: "Mung beans", link: "#" },
      { name: "Pigeon peas", link: "#" },
      { name: "Pink beans", link: "#" },
      { name: "Pinto beans", link: "#" },
      { name: "Puffed rice", link: "#" },
      { name: "Pulses", link: "#" },
      { name: "red kidney beans", link: "#" },
      { name: "Red Lentils", link: "#" },
      { name: "Romano beans", link: "#" },
      { name: "Scarlet runner beans", link: "#" },
      { name: "Split Bengal Gram", link: "#" },
      { name: "Tongue of fire beans", link: "#" },
      { name: "Trout beans", link: "#" },
      { name: "Turkish/ Dew Gram Beans", link: "#" },
      { name: "Vetches", link: "#" },
      { name: "White kidney beans", link: "#" },
      { name: "White navy beans", link: "#" },
      { name: "Yellow beans", link: "#" },
      { name: "Yellow peas", link: "#" },
      { name: "Yellow- eyed peas", link: "#" },
    ],
  },
  {
    id: "MEA",
    heading: "meat/eggs",
    items: [
      { name: "Anchovy", link: "#" },
      { name: "Bacon", link: "#" },
      { name: "Beef", link: "#" },
      { name: "Bison", link: "#" },
      { name: "Caribou", link: "#" },
      { name: "Cats", link: "#" },
      { name: "Chicken", link: "#" },
      { name: "Cornish game hen", link: "#" },
      { name: "Dogs", link: "#" },
      { name: "Duck", link: "#" },
      { name: "Eggs", link: "#" },
      { name: "Emu", link: "#" },
      { name: "Goat", link: "#" },
      { name: "Goose", link: "#" },
      { name: "Grouse", link: "#" },
      { name: "Ham", link: "#" },
      { name: "Horses", link: "#" },
      { name: "Kangaroo", link: "#" },
      { name: "Lamb", link: "#" },
      { name: "Lobster", link: "#" },
      { name: "Meat/eggs/poultry", link: "#" },
      { name: "Mutton", link: "#" },
      { name: "Ostrich", link: "#" },
      { name: "Pastrami", link: "#" },
      { name: "Pheasant", link: "#" },
      { name: "Pig", link: "#" },
      { name: "Pork", link: "#" },
      { name: "Rabbit", link: "#" },
      { name: "Salami", link: "#" },
      { name: "Squab", link: "#" },
      { name: "Turkey", link: "#" },
      { name: "Veal", link: "#" },
      { name: "Venison", link: "#" },
      { name: "Wild boar", link: "#" },
    ],
  },
  {
    id: "SPI",
    heading: "spices",
    items: [
      { name: "Ajwain", link: "#" },
      { name: "Allspice", link: "#" },
      { name: "Ancho chiles", link: "#" },
      { name: "Anise", link: "#" },
      { name: "Annatto", link: "#" },
      { name: "Arrowroot powder", link: "#" },
      { name: "Asafoetida", link: "#" },
      { name: "Baharat", link: "#" },
      { name: "Bay leaf", link: "#" },
      { name: "Beetroot powder", link: "#" },
      { name: "Bell peppers", link: "#" },
      { name: "Black pepper", link: "#" },
      { name: "Cacao", link: "#" },
      { name: "Caraway", link: "#" },
      { name: "Cardamom", link: "#" },
      { name: "Cayenne pepper", link: "#" },
      { name: "Celery salt", link: "#" },
      { name: "Chaat masala", link: "#" },
      { name: "Chiles", link: "#" },
      { name: "Chinese cinnamon", link: "#" },
      { name: "Cinnamon", link: "#" },
      { name: "Citric acid", link: "#" },
      { name: "Clove", link: "#" },
      { name: "Cubeb", link: "#" },
      { name: "Cubeb berry", link: "#" },
      { name: "Cumin", link: "#" },
      { name: "Curry powder", link: "#" },
      { name: "Fennel flower", link: "#" },
      { name: "Fenugreek", link: "#" },
      { name: "File powder", link: "#" },
      { name: "Furikake seasoning", link: "#" },
      { name: "Galangal root powder", link: "#" },
      { name: "Garam masala", link: "#" },
      { name: "Garlic", link: "#" },
      { name: "Ghost pepper", link: "#" },
      { name: "Ginger", link: "#" },
      { name: "Gochugaru", link: "#" },
      { name: "Grains of paradise", link: "#" },
      { name: "Green hatch chiles", link: "#" },
      { name: "Honey", link: "#" },
      { name: "Horseradish powder", link: "#" },
      { name: "Kaffir lime", link: "#" },
      { name: "Kampot peppercorns", link: "#" },
      { name: "Long pepper", link: "#" },
      { name: "Mace", link: "#" },
      { name: "Malheb", link: "#" },
      { name: "Maple sugar", link: "#" },
      { name: "Maras pepper", link: "#" },
      { name: "Nigella sativa", link: "#" },
      { name: "Nutmeg", link: "#" },
      { name: "Onion powder", link: "#" },
      { name: "Paprika", link: "#" },
      { name: "Pasilla", link: "#" },
      { name: "Porcini powder", link: "#" },
      { name: "Red peppers", link: "#" },
      { name: "Rose petals", link: "#" },
      { name: "Saffron", link: "#" },
      { name: "Salt", link: "#" },
      { name: "Sansho", link: "#" },
      { name: "Sesame", link: "#" },
      { name: "Shallots", link: "#" },
      { name: "Shichimi togarashi", link: "#" },
      { name: "Spices", link: "#" },
      { name: "Star anise", link: "#" },
      { name: "Turmeric", link: "#" },
      { name: "Urfa biber", link: "#" },
      { name: "Vanilla", link: "#" },
      { name: "Vinegar", link: "#" },
      { name: "Wasabi", link: "#" },
      { name: "Za’atar", link: "#" },
    ],
  },
  {
    id: "SEA",
    heading: "seafood",
    items: [
      { name: "anchovies", link: "#" },
      { name: "barracuda", link: "#" },
      { name: "Basa", link: "#" },
      { name: "Bass", link: "#" },
      { name: "Black cod/Sablefish", link: "#" },
      { name: "Blowfish", link: "#" },
      { name: "Bluefish", link: "#" },
      { name: "Bombay duck", link: "#" },
      { name: "Bream", link: "#" },
      { name: "Brill", link: "#" },
      { name: "Butter fish", link: "#" },
      { name: "Catfish", link: "#" },
      { name: "Caviar", link: "#" },
      { name: "Clam", link: "#" },
      { name: "Cockle", link: "#" },
      { name: "Cod", link: "#" },
      { name: "Conch", link: "#" },
      { name: "Crab", link: "#" },
      { name: "Crayfish", link: "#" },
      { name: "Cuttlefish", link: "#" },
      { name: "Dogfish", link: "#" },
      { name: "Dolphin", link: "#" },
      { name: "Dorade", link: "#" },
      { name: "Eel", link: "#" },
      { name: "Flounder", link: "#" },
      { name: "Grouper", link: "#" },
      { name: "Haddock", link: "#" },
      { name: "Hake", link: "#" },
      { name: "Halibut", link: "#" },
      { name: "Herring", link: "#" },
      { name: "Ikura", link: "#" },
      { name: "Ilish", link: "#" },
      { name: "John Dory", link: "#" },
      { name: "Kazunoko", link: "#" },
      { name: "Lamprey", link: "#" },
      { name: "Langostino", link: "#" },
      { name: "Lingcod", link: "#" },
      { name: "Lobster", link: "#" },
      { name: "Loco", link: "#" },
      { name: "Lumpfish roe", link: "#" },
      { name: "Mackerel", link: "#" },
      { name: "Mahi Mahi", link: "#" },
      { name: "Masago", link: "#" },
      { name: "Monkfish", link: "#" },
      { name: "Mullet", link: "#" },
      { name: "Mussel", link: "#" },
      { name: "Nautilus", link: "#" },
      { name: "Octopus", link: "#" },
      { name: "Orange roughy", link: "#" },
      { name: "Oyster", link: "#" },
      { name: "Parrotfish", link: "#" },
      { name: "Patagonian toothfish", link: "#" },
      { name: "Perch", link: "#" },
      { name: "Periwinkle", link: "#" },
      { name: "Pike", link: "#" },
      { name: "Pilchard", link: "#" },
      { name: "Pollock", link: "#" },
      { name: "Pomfret", link: "#" },
      { name: "Pompano", link: "#" },
      { name: "Prawns", link: "#" },
      { name: "Sablefish", link: "#" },
      { name: "Salmon", link: "#" },
      { name: "Sanddab", link: "#" },
      { name: "Sardine", link: "#" },
      { name: "Scallop", link: "#" },
      { name: "Sea bass", link: "#" },
      { name: "Sea cucumber", link: "#" },
      { name: "Seafood", link: "#" },
      { name: "Seal", link: "#" },
      { name: "Shad", link: "#" },
      { name: "Shad roe", link: "#" },
      { name: "Shark", link: "#" },
      { name: "Shrimp", link: "#" },
      { name: "Skate", link: "#" },
      { name: "Smelt", link: "#" },
      { name: "Snakehead", link: "#" },
      { name: "Snapper", link: "#" },
      { name: "Sole", link: "#" },
      { name: "Sprat", link: "#" },
      { name: "Squid", link: "#" },
      { name: "Sturgeon", link: "#" },
      { name: "Surimi", link: "#" },
      { name: "Swordfish", link: "#" },
      { name: "Tilapia", link: "#" },
      { name: "Tilefish", link: "#" },
      { name: "Tobiko", link: "#" },
      { name: "Trout", link: "#" },
      { name: "Tuna", link: "#" },
      { name: "Turbot", link: "#" },
      { name: "Uni", link: "#" },
      { name: "Wahoo", link: "#" },
      { name: "Whale", link: "#" },
      { name: "Whitebait", link: "#" },
      { name: "Whitefish", link: "#" },
      { name: "Whiting", link: "#" },
      { name: "Witch", link: "#" },
    ],
  },
  {
    id: "OIL",
    heading: "oilseeds",
    items: [
      { name: "Apricot", link: "#" },
      { name: "Canola", link: "#" },
      { name: "Castor beans", link: "#" },
      { name: "Chia seeds", link: "#" },
      { name: "Coconut", link: "#" },
      { name: "Copra", link: "#" },
      { name: "Cotton seed", link: "#" },
      { name: "Crambe", link: "#" },
      { name: "Flax", link: "#" },
      { name: "Flaxseed", link: "#" },
      { name: "Hemp seeds", link: "#" },
      { name: "Linseeds", link: "#" },
      { name: "Meadowfoam", link: "#" },
      { name: "Mustard", link: "#" },
      { name: "Niger", link: "#" },
      { name: "Oil palm", link: "#" },
      { name: "Oilseeds", link: "#" },
      { name: "Peanut", link: "#" },
      { name: "Poppy seeds", link: "#" },
      { name: "Pumpkin seeds", link: "#" },
      { name: "Rapeseed", link: "#" },
      { name: "Safflower", link: "#" },
      { name: "Sesame", link: "#" },
      { name: "Shea", link: "#" },
      { name: "Soybeans", link: "#" },
      { name: "Sunflower", link: "#" },
      { name: "Tonka bean", link: "#" },
      { name: "Tung", link: "#" },
      { name: "Vernonia", link: "#" },
    ],
  },
  {
    id: "NUT",
    heading: "nuts",
    items: [
      { name: "Acorns", link: "#" },
      { name: "Almonds", link: "#" },
      { name: "Areca nuts", link: "#" },
      { name: "Baru nuts", link: "#" },
      { name: "Beech", link: "#" },
      { name: "Black walnuts", link: "#" },
      { name: "Brazil nuts", link: "#" },
      { name: "Bread nuts", link: "#" },
      { name: "Cacao", link: "#" },
      { name: "Canarium nut", link: "#" },
      { name: "Candlenut", link: "#" },
      { name: "Cashews", link: "#" },
      { name: "Cedar nuts", link: "#" },
      { name: "Chestnuts", link: "#" },
      { name: "Chilean hazel", link: "#" },
      { name: "Coconut", link: "#" },
      { name: "Gabon nut", link: "#" },
      { name: "Gingko nuts", link: "#" },
      { name: "Hazelnuts", link: "#" },
      { name: "Heartnut", link: "#" },
      { name: "Jack nuts", link: "#" },
      { name: "Jelly palm nuts", link: "#" },
      { name: "Karuka", link: "#" },
      { name: "Kola nuts", link: "#" },
      { name: "Kurrajong", link: "#" },
      { name: "Macadamia nuts", link: "#" },
      { name: "Malabar chestnut", link: "#" },
      { name: "Marcona almonds", link: "#" },
      { name: "Mongongo", link: "#" },
      { name: "Nuts", link: "#" },
      { name: "Peanuts", link: "#" },
      { name: "Pecans", link: "#" },
      { name: "Pekea nuts", link: "#" },
      { name: "Pili nuts", link: "#" },
      { name: "Pine nuts", link: "#" },
      { name: "Pistachios", link: "#" },
      { name: "Red bopple nut", link: "#" },
      { name: "Roasted nuts", link: "#" },
      { name: "Salted nuts", link: "#" },
      { name: "Seasoned nuts", link: "#" },
      { name: "Soy nuts", link: "#" },
      { name: "Tiger nuts", link: "#" },
      { name: "Walnuts", link: "#" },
    ],
  },
  {
    id: "DAI",
    heading: "dairy",
    items: [
      { name: "Amasi", link: "#" },
      { name: "Anthotyros", link: "#" },
      { name: "Blaand", link: "#" },
      { name: "Buffalo milk", link: "#" },
      { name: "Butter", link: "#" },
      { name: "Butterfat", link: "#" },
      { name: "Buttermilk", link: "#" },
      { name: "Camel milk", link: "#" },
      { name: "Casein", link: "#" },
      { name: "Cheese", link: "#" },
      { name: "Clabber", link: "#" },
      { name: "Clotted cream", link: "#" },
      { name: "Condensed milk", link: "#" },
      { name: "Cottage cheese", link: "#" },
      { name: "Cow milk", link: "#" },
      { name: "Cream", link: "#" },
      { name: "Cream cheese", link: "#" },
      { name: "Cuajada", link: "#" },
      { name: "Curd", link: "#" },
      { name: "Custard", link: "#" },
      { name: "Dairy products", link: "#" },
      { name: "Feta", link: "#" },
      { name: "Filmjoik", link: "#" },
      { name: "Gelato", link: "#" },
      { name: "Ghee", link: "#" },
      { name: "Goat’s milk", link: "#" },
      { name: "Horse milk", link: "#" },
      { name: "Ice cream", link: "#" },
      { name: "Kaymak", link: "#" },
      { name: "Khoa", link: "#" },
      { name: "Kulfi", link: "#" },
      { name: "Kumis", link: "#" },
      { name: "Lassi", link: "#" },
      { name: "Leben", link: "#" },
      { name: "Malai", link: "#" },
      { name: "Matzoon", link: "#" },
      { name: "Mozzarella", link: "#" },
      { name: "Paneer", link: "#" },
      { name: "Powdered milk", link: "#" },
      { name: "Pytia", link: "#" },
      { name: "Qatiq", link: "#" },
      { name: "Quark", link: "#" },
      { name: "Reindeer milk", link: "#" },
      { name: "Ricotta", link: "#" },
      { name: "Ryazhenka", link: "#" },
      { name: "Sarasson", link: "#" },
      { name: "Sheep milk", link: "#" },
      { name: "Skyr", link: "#" },
      { name: "So", link: "#" },
      { name: "Sour cream", link: "#" },
      { name: "Surmjolk", link: "#" },
      { name: "Tarhana", link: "#" },
      { name: "Vaccenic acid", link: "#" },
      { name: "Varenets", link: "#" },
      { name: "Whey", link: "#" },
      { name: "Whipped cream", link: "#" },
      { name: "Yak butter", link: "#" },
      { name: "Yak milk", link: "#" },
      { name: "Ymer", link: "#" },
      { name: "Yogurt", link: "#" },
    ],
  },
  {
    id: "HER",
    heading: "herbs",
    items: [
      { name: "Basil", link: "#" },
      { name: "Bay Laurel", link: "#" },
      { name: "Bay leaves", link: "#" },
      { name: "Beefsteak plant", link: "#" },
      { name: "Borage", link: "#" },
      { name: "Catnip", link: "#" },
      { name: "Chamomile", link: "#" },
      { name: "Chervil", link: "#" },
      { name: "Chicory", link: "#" },
      { name: "Chives", link: "#" },
      { name: "Cicely", link: "#" },
      { name: "Cilantro", link: "#" },
      { name: "Cinquefoil", link: "#" },
      { name: "Columbine", link: "#" },
      { name: "Common rue", link: "#" },
      { name: "Common sage", link: "#" },
      { name: "Coriander", link: "#" },
      { name: "Dandelion", link: "#" },
      { name: "dill", link: "#" },
      { name: "Fennel", link: "#" },
      { name: "Feverfew", link: "#" },
      { name: "Foxglove", link: "#" },
      { name: "Garlic", link: "#" },
      { name: "Ginger", link: "#" },
      { name: "Ginkgo biloba", link: "#" },
      { name: "Ginseng", link: "#" },
      { name: "Golden rod", link: "#" },
      { name: "Herbs", link: "#" },
      { name: "Horehound", link: "#" },
      { name: "Horseradish", link: "#" },
      { name: "Hyssop", link: "#" },
      { name: "Lavender", link: "#" },
      { name: "Lemon balm", link: "#" },
      { name: "Lemon beebrush", link: "#" },
      { name: "Lemon verbena", link: "#" },
      { name: "Lemongrass", link: "#" },
      { name: "Liquorice", link: "#" },
      { name: "Lovage", link: "#" },
      { name: "Marjoram", link: "#" },
      { name: "Mexican tea", link: "#" },
      { name: "Mint", link: "#" },
      { name: "Mugwort", link: "#" },
      { name: "Myrtle", link: "#" },
      { name: "Norwegian angelica", link: "#" },
      { name: "Oregano", link: "#" },
      { name: "Parsley", link: "#" },
      { name: "Peppermint", link: "#" },
      { name: "Plantago", link: "#" },
      { name: "Poppy", link: "#" },
      { name: "Rosemary", link: "#" },
      { name: "Salad burnet", link: "#" },
      { name: "Sorrel", link: "#" },
      { name: "Spearmint", link: "#" },
      { name: "Sweet Cicely", link: "#" },
      { name: "Symphytum", link: "#" },
      { name: "Tarragon", link: "#" },
      { name: "Thyme", link: "#" },
      { name: "Turmeric", link: "#" },
      { name: "Valerian", link: "#" },
      { name: "Viola", link: "#" },
      { name: "Winter savory", link: "#" },
      { name: "Woodruff", link: "#" },
      { name: "Woodruffe", link: "#" },
      { name: "Yarrow", link: "#" },
    ],
  },
  {
    id: "FOD",
    heading: "fodder",
    items: [
      { name: "Alfalfa", link: "#" },
      { name: "Bagasse", link: "#" },
      { name: "Barley", link: "#" },
      { name: "Beets", link: "#" },
      { name: "Biochar", link: "#" },
      { name: "Bran", link: "#" },
      { name: "Bran of barley", link: "#" },
      { name: "Bran of wheat", link: "#" },
      { name: "Cabbage", link: "#" },
      { name: "Carrots", link: "#" },
      { name: "Cattle cake", link: "#" },
      { name: "Chaff waste", link: "#" },
      { name: "Copra waste", link: "#" },
      { name: "Cottonseed press cake", link: "#" },
      { name: "Fish meal", link: "#" },
      { name: "Fodder", link: "#" },
      { name: "Freshly cut grass", link: "#" },
      { name: "Grass/lawn clipping", link: "#" },
      { name: "Green maize", link: "#" },
      { name: "Green sorghum", link: "#" },
      { name: "Groundnut press cake", link: "#" },
      { name: "Hay", link: "#" },
      { name: "Horse gram", link: "#" },
      { name: "Leaves", link: "#" },
      { name: "Meat and bone meal", link: "#" },
      { name: "Millet", link: "#" },
      { name: "Molasses", link: "#" },
      { name: "Native green grass", link: "#" },
      { name: "Oats", link: "#" },
      { name: "Oligosaccharides", link: "#" },
      { name: "Peanut press cake", link: "#" },
      { name: "Pellets", link: "#" },
      { name: "Processed insects", link: "#" },
      { name: "Pumpkins", link: "#" },
      { name: "Ryegrass", link: "#" },
      { name: "Safflower press cake", link: "#" },
      { name: "Seaweed", link: "#" },
      { name: "Seeds and grains", link: "#" },
      { name: "Silage", link: "#" },
      { name: "Single cell protein", link: "#" },
      { name: "Sorghum", link: "#" },
      { name: "Soybean press cake", link: "#" },
      { name: "Sprouted grains/legumes", link: "#" },
      { name: "Stover waste", link: "#" },
      { name: "Straw waste", link: "#" },
      { name: "Sugar beet waste", link: "#" },
      { name: "Sunflower press cake", link: "#" },
      { name: "Swedes", link: "#" },
      { name: "Turnips", link: "#" },
      { name: "Yeast extract", link: "#" },
    ],
  },
];

export default CatMenu;
