import Placeholder from "../../../res/categoryScroll/placeholder.svg";

const SellingNowData = {
  bulk: [
    {
      id: "d22e33d2",
      img: Placeholder,
      nm: "Tomato",
      ty: "Seasonal",
      ve: "Hybrid",
      qty: 100,
      qtU: "Kg",
      tm: "24 hr 39 mins",
      bp: 12.5,
      bpU: "Kg",
      sl: 8,
      slU: "days",
      bQ: 94,
      p: true,
    },
    {
      id: "d25433d2",
      img: Placeholder,
      nm: "Asofina",
      ty: "Seasonal",
      ve: "BE-2332",
      qty: 100,
      qtU: "Kg",
      tm: "24 hr 39 mins",
      bp: 110,
      bpU: "gram",
      sl: 23,
      slU: "hours",
      bQ: 24,
      p: false,
    },
  ],
  retail: [
    {
      id: "d22e33d2",
      img: Placeholder,
      nm: "Tomato",
      ty: "Seasonal",
      ve: "Hybrid",
      qty: 100,
      qtU: "Kg",
      tm: null,
      bp: 12.5,
      bpU: "Kg",
      sl: 8,
      slU: "days",
      ts: 1593549718,
      p: true,
    },
    {
      id: "d25433d2",
      img: Placeholder,
      nm: "Asofina",
      ty: "Seasonal",
      ve: "BE-2332",
      qty: 100,
      qtU: "Kg",
      tm: "24 hr 39 mins",
      bp: 110,
      bpU: "gram",
      sl: 23,
      slU: "hours",
      ts: 1593549718,
      p: false,
    },
  ],
};

export default SellingNowData;
