# Generated by Django 3.0.2 on 2020-07-29 04:53

from django.db import migrations
import os
from sys import path
from django.core import serializers

fixture_dir = os.path.abspath(os.path.join(
    os.path.dirname(__file__), '../fixtures'))

# TODO: Remember to change the file name
fixture_filename = 'initial_data.json'


def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)

    fixture = open(fixture_file, 'rb')
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    fixture.close()


def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    # TODO: change the app and model name
    MyModel = apps.get_model("api", "CustomUser")
    MyModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        # TODO: change the app and model name
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
