import Placeholder from "../../../res/categoryScroll/placeholder.svg";

const FarmerSliderList = [
  {
    id: "123456",
    name: "Sakshi Murgi",
    place: "Aliganj, Bhagalpur",
    dpUrl: Placeholder,
    rating: "3.6",
    profileUrl: "#",
    productUrl: "#",
    isAd: false,
  },
  {
    id: "126456",
    name: "Raja Abhay Singh",
    place: "Tada, Chittoor",
    dpUrl: Placeholder,
    rating: "0",
    profileUrl: "#",
    productUrl: "#",
    isAd: false,
  },
  {
    id: "134456",
    name: "Abhijit Patel",
    place: "Sri City, Chittoor",
    dpUrl: Placeholder,
    rating: "4.9",
    profileUrl: "#",
    productUrl: "#",
    isAd: false,
  },
  {
    id: "123466",
    name: "Ram Charan",
    place: "Kittu, Nellore",
    dpUrl: Placeholder,
    rating: "4.2",
    profileUrl: "#",
    productUrl: "#",
    isAd: false,
  },
  {
    id: "123451",
    name: "Abhay Singh",
    place: "Gunnabari, Hydrabad",
    dpUrl: Placeholder,
    rating: "4.5",
    profileUrl: "#",
    productUrl: "#",
    isAd: true,
  },
  {
    id: "802391",
    name: "Bedu Farm",
    place: "Aliganj, Bhagalpur",
    dpUrl: Placeholder,
    rating: "3.5",
    profileUrl: "#",
    productUrl: "#",
    isAd: false,
  },
  {
    id: "372189",
    name: "Suraj Kumar Prem",
    place: "Aliganj, Bhagalpur",
    dpUrl: Placeholder,
    rating: "5",
    profileUrl: "#",
    productUrl: "#",
    isAd: true,
  },
  {
    id: "231451",
    name: "Abhijit Patel",
    place: "Sri City, Chittoor",
    dpUrl: Placeholder,
    rating: "4.9",
    profileUrl: "#",
    productUrl: "#",
    isAd: false,
  },
  {
    id: "546798",
    name: "Ram Charan",
    place: "Kittu, Nellore",
    dpUrl: Placeholder,
    rating: "4.2",
    profileUrl: "#",
    productUrl: "#",
    isAd: false,
  },
  {
    id: "412709",
    name: "Abhay Singh",
    place: "Gunnabari, Hydrabad",
    dpUrl: Placeholder,
    rating: "4.5",
    profileUrl: "#",
    productUrl: "#",
    isAd: true,
  },
  {
    id: "218903",
    name: "Bedu Farm",
    place: "Aliganj, Bhagalpur",
    dpUrl: Placeholder,
    rating: "3.5",
    profileUrl: "#",
    productUrl: "#",
    isAd: false,
  },
  {
    id: "687234",
    name: "Suraj Kumar Prem",
    place: "Aliganj, Bhagalpur",
    dpUrl: Placeholder,
    rating: "5",
    profileUrl: "#",
    productUrl: "#",
    isAd: true,
  },
];

export default FarmerSliderList;
