import Placeholder from "../../../res/categoryScroll/placeholder.svg";

const AdCategoryData1 = {
  id: "rc8r3",
  titleLeft1: "Grains and Pulses",
  titleLeft2: "buy the taste of India...",
  titleRight1: "",
  titleRight2: "View all",
  bgImage: "linear-gradient(#ffffff, #0f4153, #ffffff)",
  bgImagePC: "linear-gradient(#ffffff, #cfcfcf, #ffffff)",
  // btnColor: "linear-gradient(#18607a, #0c3b4d)",
  fontColor: "#000000",
  fontColorPC: "#000000",
  graphicsLeftUrl: "none",
  graphicsRightUrl: "none",
  viewAllLink: "#",

  adList: [
    {
      adId: "4376f",
      offerVal: "Upto 30% off",
      adImgUrl: Placeholder,
      adTitle: "Grapefruit",
      adDesc: "Tropica juicy fruit",
      adSubDesc: "from ₹ 59.00 / kg",
      adLink: "#",
    },
    {
      adId: "3ff3",
      offerVal: "Upto 30% off",
      adImgUrl: Placeholder,
      adTitle: "Banana",
      adDesc: "Hign calorie from babanana ",
      adSubDesc: "from ₹ 59.00 / kg",
      adLink: "#",
    },
    {
      adId: "46g4g",
      offerVal: "Upto 30% off",
      adImgUrl: Placeholder,
      adTitle: "Mango",
      adDesc: "Seasonal juicy",
      adSubDesc: "from ₹ 59.00 / kg",
      adLink: "#",
    },
    {
      adId: "gf435g",
      offerVal: "Upto 30% off",
      adImgUrl: Placeholder,
      adTitle: "Apple",
      adDesc: "Himalyan freshness",
      adSubDesc: "from ₹ 59.00 / kg",
      adLink: "#",
    },
    {
      adId: "f334",
      offerVal: "Upto 30% off",
      adImgUrl: Placeholder,
      adTitle: "Mango",
      adDesc: "Seasonal juicy",
      adSubDesc: "from ₹ 59.00 / kg",
      adLink: "#",
    },
    {
      adId: "g45frd3rf",
      offerVal: "Upto 30% off",
      adImgUrl: Placeholder,
      adTitle: "Apple",
      adDesc: "Himalyan freshness",
      adSubDesc: "from ₹ 59.00 / kg",
      adLink: "#",
    },
  ],
};

export default AdCategoryData1;
