import Placeholder from "../../res/productSlider/placeholder.jpg";

const SearchResultData = {
  query: "Tomato",
  loc: "Aliganj Maheshpur, Ram Mandal Lane, Bhagalpur, 812005",
  lat: 34,
  long: 243,
  totRes: 21332,
  currPage: 2,
  resPerPage: 40,
  sort: "price l-h",
  bulk: true,
  normal: true,
  filters: [],
  dataNormal: [
    {
      id: "8C684734BC7634BC5",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "37",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "C3389764B827C683C",
      isFresh: false,
      imageURL: Placeholder,
      name: "Banana",
      otherSellers: "12",
      type: "Hybrid",
      category: "Fruits",
      basePrice: "24.00",
      pricePerUnit: "dozen",
      addedDigit: "3",
      addedUnit: "hours",
      location: "Sanhoula, Bhagalpur",
      isNegotiable: false,
      sellerId: "4c5t5f4",
    },
    {
      id: "C2874C2CB46327B6",
      isFresh: true,
      imageURL: Placeholder,
      name: "Brinjal",
      otherSellers: "2",
      type: "Seasonal",
      category: "Vegetable",
      basePrice: "19.00",
      pricePerUnit: "Kg",
      addedDigit: "1",
      addedUnit: "day(s)",
      location: "Tada, Sri City",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "V30J3V430N84T9",
      isFresh: false,
      imageURL: Placeholder,
      name: "Rice",
      otherSellers: "20",
      type: "Sonam-Hybrid (C-212)",
      category: "Grains",
      basePrice: "34.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: false,
      sellerId: "X874BC36483",
    },
    {
      id: "384HNT3N43H4985T",
      isFresh: false,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "30485NT7C547N4389",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "90348V57T85CM4959",
      isFresh: false,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: false,
      sellerId: "X874BC36483",
    },
    {
      id: "9058C7T3454895T",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "C04N7543CNX893N45",
      isFresh: false,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "94587NV958NC5VY458H",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "8C684734BC7634BC5",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "37",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "C3389764B827C683C",
      isFresh: false,
      imageURL: Placeholder,
      name: "Banana",
      otherSellers: "12",
      type: "Hybrid",
      category: "Fruits",
      basePrice: "24.00",
      pricePerUnit: "dozen",
      addedDigit: "3",
      addedUnit: "hours",
      location: "Sanhoula, Bhagalpur",
      isNegotiable: false,
      sellerId: "4c5t5f4",
    },
    {
      id: "C2874C2CB46327B6",
      isFresh: true,
      imageURL: Placeholder,
      name: "Brinjal",
      otherSellers: "2",
      type: "Seasonal",
      category: "Vegetable",
      basePrice: "19.00",
      pricePerUnit: "Kg",
      addedDigit: "1",
      addedUnit: "day(s)",
      location: "Tada, Sri City",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "V30J3V430N84T9",
      isFresh: false,
      imageURL: Placeholder,
      name: "Rice",
      otherSellers: "20",
      type: "Sonam-Hybrid (C-212)",
      category: "Grains",
      basePrice: "34.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: false,
      sellerId: "X874BC36483",
    },
    {
      id: "384HNT3N43H4985T",
      isFresh: false,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "30485NT7C547N4389",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "90348V57T85CM4959",
      isFresh: false,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: false,
      sellerId: "X874BC36483",
    },
    {
      id: "9058C7T3454895T",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "C04N7543CNX893N45",
      isFresh: false,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "94587NV958NC5VY458H",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "8C684734BC7634BC5",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "37",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "C3389764B827C683C",
      isFresh: false,
      imageURL: Placeholder,
      name: "Banana",
      otherSellers: "12",
      type: "Hybrid",
      category: "Fruits",
      basePrice: "24.00",
      pricePerUnit: "dozen",
      addedDigit: "3",
      addedUnit: "hours",
      location: "Sanhoula, Bhagalpur",
      isNegotiable: false,
      sellerId: "4c5t5f4",
    },
    {
      id: "C2874C2CB46327B6",
      isFresh: true,
      imageURL: Placeholder,
      name: "Brinjal",
      otherSellers: "2",
      type: "Seasonal",
      category: "Vegetable",
      basePrice: "19.00",
      pricePerUnit: "Kg",
      addedDigit: "1",
      addedUnit: "day(s)",
      location: "Tada, Sri City",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "V30J3V430N84T9",
      isFresh: false,
      imageURL: Placeholder,
      name: "Rice",
      otherSellers: "20",
      type: "Sonam-Hybrid (C-212)",
      category: "Grains",
      basePrice: "34.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: false,
      sellerId: "X874BC36483",
    },
    {
      id: "384HNT3N43H4985T",
      isFresh: false,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "30485NT7C547N4389",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "90348V57T85CM4959",
      isFresh: false,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: false,
      sellerId: "X874BC36483",
    },
    {
      id: "9058C7T3454895T",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "C04N7543CNX893N45",
      isFresh: false,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
    {
      id: "94587NV958NC5VY458H",
      isFresh: true,
      imageURL: Placeholder,
      name: "Tomato",
      otherSellers: "20",
      type: "Hybrid",
      category: "Vegetable",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      addedDigit: "36",
      addedUnit: "minutes",
      location: "Aliganj, Bhagalpur",
      isNegotiable: true,
      sellerId: "X874BC36483",
    },
  ],
  dataBulk: [
    {
      id: "8C684734BC7634BC5",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: false,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "mg",
      maxBookVal: "1",
      maxBookValUnit: "kg",
      soldPercent: "63.6",
    },
    {
      id: "MNB231",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "0",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "GJH432G43J2H",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "SDFGU432",
      imageURL: Placeholder,
      name: "Rice",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "YRNR44CR4",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "RHUFR",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "39J43N8",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "DCV5F6B7G8YN",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "C678BC",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "B34YC834TBG3R",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "8C684734BC7634BC5",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: false,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "mg",
      maxBookVal: "1",
      maxBookValUnit: "kg",
      soldPercent: "63.6",
    },
    {
      id: "MNB231",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "0",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "GJH432G43J2H",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "SDFGU432",
      imageURL: Placeholder,
      name: "Rice",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "YRNR44CR4",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "RHUFR",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "39J43N8",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "DCV5F6B7G8YN",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "C678BC",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
    {
      id: "B34YC834TBG3R",
      imageURL: Placeholder,
      name: "Tomato",
      breed: "Hybrid",
      location: "Aliganj, Bhagalpur",
      category: "Vegetable",
      lotSizeDigit: "500",
      lotSizeUnit: "Kg",
      basePrice: "17.00",
      pricePerUnit: "Kg",
      sellerId: "X874BC36483",
      sellerRating: "4.2",
      isNegotiable: true,
      delTime: "34 hours 32 minutes",
      minBookVal: "500",
      minBookValUnit: "g",
      maxBookVal: "100",
      maxBookValUnit: "kg",
      soldPercent: "23.6",
    },
  ],
};

export default SearchResultData;
