const BannerUrls = {
  url: [
    "https://happyfarmmedia.imfast.io/images/banner/Banner1.png",
    "https://happyfarmmedia.imfast.io/images/banner/Banner2.png",
    "https://happyfarmmedia.imfast.io/images/banner/Banner4.png",
    "https://happyfarmmedia.imfast.io/images/banner/Banner5.png",
    "https://happyfarmmedia.imfast.io/images/banner/DairyBanner1.png",
    "https://happyfarmmedia.imfast.io/images/banner/DairyBanner2.png",
    "https://happyfarmmedia.imfast.io/images/banner/Fish.png",
    "https://happyfarmmedia.imfast.io/images/banner/FlourBanner1.png",
    "https://happyfarmmedia.imfast.io/images/banner/FlourBanner2.png",
    "https://happyfarmmedia.imfast.io/images/banner/FlowerBanner1.png",
    "https://happyfarmmedia.imfast.io/images/banner/FlowerBanner2.png",
    "https://happyfarmmedia.imfast.io/images/banner/FlowerBanner3.png",
    "https://happyfarmmedia.imfast.io/images/banner/FruitsBanner1.png",
    "https://happyfarmmedia.imfast.io/images/banner/FruitsBanner2.png",
    "https://happyfarmmedia.imfast.io/images/banner/FruitsBanner3.jpg",
    "https://happyfarmmedia.imfast.io/images/banner/FruitsBanner4.jpeg",
    "https://happyfarmmedia.imfast.io/images/banner/Herb_banner1.png",
    "https://happyfarmmedia.imfast.io/images/banner/Herb_banner2.png",
    "https://happyfarmmedia.imfast.io/images/banner/MeatBanner1.png",
    "https://happyfarmmedia.imfast.io/images/banner/PulsesBanner1.png",
    "https://happyfarmmedia.imfast.io/images/banner/vegetableBanner1.png",
    "https://happyfarmmedia.imfast.io/images/banner/vegetablebanner2.png",
    "https://happyfarmmedia.imfast.io/images/banner/vegetableBanner3.png",
    "https://happyfarmmedia.imfast.io/images/banner/vegetableBanner4.jpeg",
    "https://happyfarmmedia.imfast.io/images/banner/vegetableBanner5.png",
    "https://happyfarmmedia.imfast.io/images/banner/Wheat1.png",
  ],
};

export default BannerUrls;
