import Placeholder from "../../../res/productSlider/placeholder.jpg";

const BuklSliderList = [
  {
    id: "8C684734BC7634BC5",
    imageURL: Placeholder,
    name: "Tomato",
    breed: "Hybrid",
    location: "Aliganj, Bhagalpur",
    category: "Vegetable",
    lotSizeDigit: "500",
    lotSizeUnit: "Kg",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    sellerId: "X874BC36483",
    sellerRating: "4.2",
    isNegotiable: false,
    delTime: "34 hours 32 minutes",
    minBookVal: "500",
    minBookValUnit: "mg",
    maxBookVal: "1",
    maxBookValUnit: "kg",
    soldPercent: "63.6",
  },
  {
    id: "MNB231",
    imageURL: Placeholder,
    name: "Tomato",
    breed: "Hybrid",
    location: "Aliganj, Bhagalpur",
    category: "Vegetable",
    lotSizeDigit: "500",
    lotSizeUnit: "Kg",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    sellerId: "X874BC36483",
    sellerRating: "0",
    isNegotiable: true,
    delTime: "34 hours 32 minutes",
    minBookVal: "500",
    minBookValUnit: "g",
    maxBookVal: "100",
    maxBookValUnit: "kg",
    soldPercent: "23.6",
  },
  {
    id: "GJH432G43J2H",
    imageURL: Placeholder,
    name: "Tomato",
    breed: "Hybrid",
    location: "Aliganj, Bhagalpur",
    category: "Vegetable",
    lotSizeDigit: "500",
    lotSizeUnit: "Kg",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    sellerId: "X874BC36483",
    sellerRating: "4.2",
    isNegotiable: true,
    delTime: "34 hours 32 minutes",
    minBookVal: "500",
    minBookValUnit: "g",
    maxBookVal: "100",
    maxBookValUnit: "kg",
    soldPercent: "23.6",
  },
  {
    id: "SDFGU432",
    imageURL: Placeholder,
    name: "Rice",
    breed: "Hybrid",
    location: "Aliganj, Bhagalpur",
    category: "Vegetable",
    lotSizeDigit: "500",
    lotSizeUnit: "Kg",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    sellerId: "X874BC36483",
    sellerRating: "4.2",
    isNegotiable: true,
    delTime: "34 hours 32 minutes",
    minBookVal: "500",
    minBookValUnit: "g",
    maxBookVal: "100",
    maxBookValUnit: "kg",
    soldPercent: "23.6",
  },
  {
    id: "YRNR44CR4",
    imageURL: Placeholder,
    name: "Tomato",
    breed: "Hybrid",
    location: "Aliganj, Bhagalpur",
    category: "Vegetable",
    lotSizeDigit: "500",
    lotSizeUnit: "Kg",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    sellerId: "X874BC36483",
    sellerRating: "4.2",
    isNegotiable: true,
    delTime: "34 hours 32 minutes",
    minBookVal: "500",
    minBookValUnit: "g",
    maxBookVal: "100",
    maxBookValUnit: "kg",
    soldPercent: "23.6",
  },
  {
    id: "RHUFR",
    imageURL: Placeholder,
    name: "Tomato",
    breed: "Hybrid",
    location: "Aliganj, Bhagalpur",
    category: "Vegetable",
    lotSizeDigit: "500",
    lotSizeUnit: "Kg",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    sellerId: "X874BC36483",
    sellerRating: "4.2",
    isNegotiable: true,
    delTime: "34 hours 32 minutes",
    minBookVal: "500",
    minBookValUnit: "g",
    maxBookVal: "100",
    maxBookValUnit: "kg",
    soldPercent: "23.6",
  },
  {
    id: "39J43N8",
    imageURL: Placeholder,
    name: "Tomato",
    breed: "Hybrid",
    location: "Aliganj, Bhagalpur",
    category: "Vegetable",
    lotSizeDigit: "500",
    lotSizeUnit: "Kg",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    sellerId: "X874BC36483",
    sellerRating: "4.2",
    isNegotiable: true,
    delTime: "34 hours 32 minutes",
    minBookVal: "500",
    minBookValUnit: "g",
    maxBookVal: "100",
    maxBookValUnit: "kg",
    soldPercent: "23.6",
  },
  {
    id: "DCV5F6B7G8YN",
    imageURL: Placeholder,
    name: "Tomato",
    breed: "Hybrid",
    location: "Aliganj, Bhagalpur",
    category: "Vegetable",
    lotSizeDigit: "500",
    lotSizeUnit: "Kg",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    sellerId: "X874BC36483",
    sellerRating: "4.2",
    isNegotiable: true,
    delTime: "34 hours 32 minutes",
    minBookVal: "500",
    minBookValUnit: "g",
    maxBookVal: "100",
    maxBookValUnit: "kg",
    soldPercent: "23.6",
  },
  {
    id: "C678BC",
    imageURL: Placeholder,
    name: "Tomato",
    breed: "Hybrid",
    location: "Aliganj, Bhagalpur",
    category: "Vegetable",
    lotSizeDigit: "500",
    lotSizeUnit: "Kg",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    sellerId: "X874BC36483",
    sellerRating: "4.2",
    isNegotiable: true,
    delTime: "34 hours 32 minutes",
    minBookVal: "500",
    minBookValUnit: "g",
    maxBookVal: "100",
    maxBookValUnit: "kg",
    soldPercent: "23.6",
  },
  {
    id: "B34YC834TBG3R",
    imageURL: Placeholder,
    name: "Tomato",
    breed: "Hybrid",
    location: "Aliganj, Bhagalpur",
    category: "Vegetable",
    lotSizeDigit: "500",
    lotSizeUnit: "Kg",
    basePrice: "17.00",
    pricePerUnit: "Kg",
    sellerId: "X874BC36483",
    sellerRating: "4.2",
    isNegotiable: true,
    delTime: "34 hours 32 minutes",
    minBookVal: "500",
    minBookValUnit: "g",
    maxBookVal: "100",
    maxBookValUnit: "kg",
    soldPercent: "23.6",
  },
];

export default BuklSliderList;
